## Data Cleaning - For Tableau Import/Map

### Import dependcies and read in csv files

In [1]:
# Import pandas

import pandas as pd

In [2]:
# Assigning the paths to our CSV files

# file = "../Resources/Pollution_clean/Clean_Pollution.csv"
file1 = "../Resources/Medicare_clean/clean_pc_state_rates_2011.csv"
file2 = "../Resources/Medicare_clean/clean_pc_state_rates_2012.csv"
file3 = "../Resources/Medicare_clean/clean_pc_state_rates_2013.csv"
file4 = "../Resources/Medicare_clean/clean_pc_state_rates_2014.csv"
file5 = "../Resources/Medicare_clean/clean_pc_state_rates_2015.csv"
file6 = "../Resources/Census_clean/clean_census_2011.csv"
file7 = "../Resources/Census_clean/clean_census_2012.csv"
file8 = "../Resources/Census_clean/clean_census_2013.csv"
file9 = "../Resources/Census_clean/clean_census_2014.csv"
file10 = "../Resources/Census_clean/clean_census_2015.csv"
file11 = "../Resources/Tableau_clean/states_lat_and_long.csv"
file12 = "../Resources/Tableau_clean/Pollution_2011.csv"
file13 = "../Resources/Tableau_clean/Pollution_2012.csv"
file14 = "../Resources/Tableau_clean/Pollution_2013.csv"
file15 = "../Resources/Tableau_clean/Pollution_2014.csv"
file16 = "../Resources/Tableau_clean/Pollution_2015.csv"

In [3]:
# Latitude and longitude: from https://developers.google.com/public-data/docs/canonical/states_csv

states = pd.read_csv(file11)
states = states.sort_values("name") 
states

   state   latitude   longitude                  name
1     AL  32.318231  -86.902298               Alabama
0     AK  63.588753 -154.493062                Alaska
3     AZ  34.048928 -111.093731               Arizona
2     AR  35.201050  -91.831833              Arkansas
4     CA  36.778261 -119.417932            California
5     CO  39.550051 -105.782067              Colorado
6     CT  41.603221  -73.087749           Connecticut
8     DE  38.910832  -75.527670              Delaware
7     DC  38.905985  -77.033418  District of Columbia
9     FL  27.664827  -81.515754               Florida
10    GA  32.157435  -82.907123               Georgia
11    HI  19.898682 -155.665857                Hawaii
13    ID  44.068202 -114.742041                 Idaho
14    IL  40.633125  -89.398528              Illinois
15    IN  40.551217  -85.602364               Indiana
12    IA  41.878003  -93.097702                  Iowa
16    KS  39.011902  -98.484246                Kansas
17    KY  37.839333  -84.270018              Kentucky
18    LA  31.244823  -92.145024             Louisiana
21    ME  45.253783  -69.445469                 Maine
20    MD  39.045755  -76.641271              Maryland
19    MA  42.407211  -71.382437         Massachusetts
22    MI  44.314844  -85.602364              Michigan
23    MN  46.729553  -94.685900             Minnesota
25    MS  32.354668  -89.398528           Mississippi
24    MO  37.964253  -91.831833              Missouri
26    MT  46.879682 -110.362566               Montana
29    NE  41.492537  -99.901813              Nebraska
33    NV  38.802610 -116.419389                Nevada
30    NH  43.193852  -71.572395         New Hampshire
31    NJ  40.058324  -74.405661            New Jersey
32    NM  34.972730 -105.032363            New Mexico
34    NY  43.299428  -74.217933              New York
27    NC  35.759573  -79.019300        North Carolina
28    ND  47.551493 -101.002012          North Dakota
35    OH  40.417287  -82.907123                  Ohio
36    OK  35.007752  -97.092877              Oklahoma
37    OR  43.804133 -120.554201                Oregon
38    PA  41.203322  -77.194525          Pennsylvania
39    PR  18.220833  -66.590149           Puerto Rico
40    RI  41.580095  -71.477429          Rhode Island
41    SC  33.836081  -81.163725        South Carolina
42    SD  43.969515  -99.901813          South Dakota
43    TN  35.517491  -86.580447             Tennessee
44    TX  31.968599  -99.901813                 Texas
45    UT  39.320980 -111.093731                  Utah
47    VT  44.558803  -72.577841               Vermont
46    VA  37.431573  -78.656894              Virginia
48    WA  47.751074 -120.740139            Washington
50    WV  38.597626  -80.454903         West Virginia
49    WI  43.784440  -88.787868             Wisconsin
51    WY  43.075968 -107.290284               Wyoming

### Medicare Data

In [4]:
# Read our data into pandas

medicare_2011 = pd.read_csv(file1)
medicare_2012 = pd.read_csv(file2)
medicare_2013 = pd.read_csv(file3)
medicare_2014 = pd.read_csv(file4)
medicare_2015 = pd.read_csv(file5)

In [5]:
medicare_2011.head()

,state_id,state_name,beneficiaries_part_b,one_ambulatory_visit,diabetic_enrollees_age_65_to_75,average_diabetic_enrollees_hemoglobin_a1c_test,average_diabetic_enrollees_eye_exam,average_diabetic_enrollees_blood_lipids_test,average_female_enrollees_age_67_to_69,average_female_age_67_to_69_mammogram,beneficiaries_part_a_eligible,leg_amputations_per_1000_enrollees,discharges_ambulatory_care_sensitive_conditions_per_1000_enrollees
0,1,Alabama,478784,82.5,69691,83.9,63.3,80.3,42267,62.8,501422,0.99,76.4
1,2,Alaska,49648,70.9,5449,74.5,55.8,66.9,5151,55.3,54928,0.81,53.1
2,3,Arizona,465298,78.2,50991,78.5,66.1,75.8,43614,64.3,501103,0.57,51.4
3,4,Arkansas,327939,80.7,40202,82.5,66.1,76.2,29290,58.3,345431,0.85,77.0
4,5,California,2238140,72.7,243999,80.6,64.1,78.0,190971,59.0,2378472,0.63,49.9

In [6]:
# Idenitfy nan values from 2013

medicare_2013.tail()

,state_id,state_name,beneficiaries_part_b,one_ambulatory_visit,diabetic_enrollees_age_65_to_75,average_diabetic_enrollees_hemoglobin_a1c_test,average_diabetic_enrollees_eye_exam,average_diabetic_enrollees_blood_lipids_test,average_female_enrollees_age_67_to_69,average_female_age_67_to_69_mammogram,beneficiaries_part_a_eligible,leg_amputations_per_1000_enrollees,discharges_ambulatory_care_sensitive_conditions_per_1000_enrollees
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Drop nan values from 2013

medicare_2013_dropped = medicare_2013.iloc[0:52]
medicare_2013_dropped.tail()

,state_id,state_name,beneficiaries_part_b,one_ambulatory_visit,diabetic_enrollees_age_65_to_75,average_diabetic_enrollees_hemoglobin_a1c_test,average_diabetic_enrollees_eye_exam,average_diabetic_enrollees_blood_lipids_test,average_female_enrollees_age_67_to_69,average_female_age_67_to_69_mammogram,beneficiaries_part_a_eligible,leg_amputations_per_1000_enrollees,discharges_ambulatory_care_sensitive_conditions_per_1000_enrollees
47,50.0,Washington,571799.0,78.9,61248.0,86.1,67.4,78.9,46515.0,60.9,634883.0,0.58,35.6
48,51.0,West Virginia,204275.0,80.9,32596.0,83.8,59.7,79.4,17716.0,58.1,225415.0,0.83,81.2
49,52.0,Wisconsin,484902.0,80.1,52893.0,90.0,70.3,84.2,39788.0,70.5,554934.0,0.64,47.9
50,53.0,Wyoming,68066.0,74.6,6475.0,75.4,62.7,60.2,5844.0,57.1,73043.0,0.67,47.9
51,99.0,United States,26755951.0,79.1,3313579.0,84.9,66.8,81.0,2251014.0,62.8,29467940.0,0.62,53.8

In [8]:
# Drop extra row tallying up the United States

medicare_2011_states = medicare_2011.iloc[0:51]
medicare_2012_states = medicare_2012.iloc[0:51]
medicare_2013_states = medicare_2013_dropped.iloc[0:51]
medicare_2014_states = medicare_2014.iloc[0:51]
medicare_2015_states = medicare_2015.iloc[0:51]
medicare_2013_states.tail()

,state_id,state_name,beneficiaries_part_b,one_ambulatory_visit,diabetic_enrollees_age_65_to_75,average_diabetic_enrollees_hemoglobin_a1c_test,average_diabetic_enrollees_eye_exam,average_diabetic_enrollees_blood_lipids_test,average_female_enrollees_age_67_to_69,average_female_age_67_to_69_mammogram,beneficiaries_part_a_eligible,leg_amputations_per_1000_enrollees,discharges_ambulatory_care_sensitive_conditions_per_1000_enrollees
46,49.0,Virginia,807461.0,82.7,107366.0,86.6,69.2,82.3,70841.0,63.0,900400.0,0.58,49.0
47,50.0,Washington,571799.0,78.9,61248.0,86.1,67.4,78.9,46515.0,60.9,634883.0,0.58,35.6
48,51.0,West Virginia,204275.0,80.9,32596.0,83.8,59.7,79.4,17716.0,58.1,225415.0,0.83,81.2
49,52.0,Wisconsin,484902.0,80.1,52893.0,90.0,70.3,84.2,39788.0,70.5,554934.0,0.64,47.9
50,53.0,Wyoming,68066.0,74.6,6475.0,75.4,62.7,60.2,5844.0,57.1,73043.0,0.67,47.9

In [9]:
# Sort Medicare dataframes by state name

medicare_2011 = medicare_2011.sort_values("state_name")  
medicare_2012 = medicare_2012.sort_values("state_name")  
medicare_2013 = medicare_2013.sort_values("state_name")  
medicare_2014 = medicare_2014.sort_values("state_name")  
medicare_2015 = medicare_2015.sort_values("state_name")

In [10]:
# Append latitude and longitude into Medicare dataframes

medicare_2011['latitude'] = states['latitude']
medicare_2011['longitude'] = states['longitude']
medicare_2012['latitude'] = states['latitude']
medicare_2012['longitude'] = states['longitude']
medicare_2013['latitude'] = states['latitude']
medicare_2013['longitude'] = states['longitude']
medicare_2014['latitude'] = states['latitude']
medicare_2014['longitude'] = states['longitude']
medicare_2015['latitude'] = states['latitude']
medicare_2015['longitude'] = states['longitude']

In [11]:
medicare_2015

,state_id,state_name,beneficiaries_part_b,one_ambulatory_visit,diabetic_enrollees_age_65_to_75,average_diabetic_enrollees_hemoglobin_a1c_test,average_diabetic_enrollees_eye_exam,average_diabetic_enrollees_blood_lipids_test,average_female_enrollees_age_67_to_69,average_female_age_67_to_69_mammogram,beneficiaries_part_a_eligible,leg_amputations_per_1000_enrollees,discharges_ambulatory_care_sensitive_conditions_per_1000_enrollees,latitude,longitude
0,1,Alabama,510586,83.3,68202,86.1,64.0,81.0,52169,63.1,404987,0.79,62.0,63.588753,-154.493062
1,2,Alaska,61807,72.2,5969,74.6,55.9,62.7,6547,55.0,51861,-0.34,36.0,32.318231,-86.902298
2,3,Arizona,549896,79.3,52974,80.4,67.3,75.1,56896,63.4,447437,0.44,36.1,35.201050,-91.831833
3,4,Arkansas,340105,81.1,37707,85.5,66.4,77.8,32771,57.9,271556,0.82,61.8,34.048928,-111.093731
4,5,California,2334245,72.9,208322,81.9,63.4,77.2,212794,59.5,1907116,0.44,36.2,36.778261,-119.417932
5,6,Colorado,362323,77.1,27684,84.2,64.3,71.1,37894,60.2,316713,0.29,31.2,39.550051,-105.782067
6,7,Connecticut,344478,79.9,29700,87.1,74.4,80.7,27111,68.0,290823,0.48,46.2,41.603221,-73.087749
7,8,Delaware,129807,85.3,16615,87.0,72.2,82.8,13551,70.3,103244,0.50,47.2,38.905985,-77.033418
8,9,District of Columbia,48159,67.3,4996,80.5,68.3,71.6,4419,61.5,47611,0.48,38.3,38.910832,-75.527670
9,10,Florida,1861794,79.8,190229,86.1,68.2,84.8,161850,67.6,1506764,0.52,53.6,27.664827,-81.515754
10,11,Georgia,748200,81.1,91559,86.2,62.8,80.3,75174,62.3,598383,0.65,50.2,32.157435,-82.907123
11,12,Hawaii,91929,74.3,9313,85.6,72.8,83.7,7891,61.0,85322,0.51,23.3,19.898682,-155.665857
12,13,Idaho,141812,76.3,13083,83.8,63.7,71.2,13012,57.3,115757,0.46,32.3,41.878003,-93.097702
13,14,Illinois,1210320,79.8,129125,86.5,65.5,79.8,108916,65.1,985698,0.56,54.8,44.068202,-114.742041
14,15,Indiana,646310,81.0,77444,86.1,61.7,76.7,62363,62.3,520025,0.69,56.8,40.633125,-89.398528
15,16,Iowa,385061,80.8,37861,90.2,76.1,79.4,34447,68.6,313976,0.47,48.9,40.551217,-85.602364
16,17,Kansas,323018,83.7,33310,86.8,72.7,74.2,29474,62.5,261764,0.53,51.3,39.011902,-98.484246
17,18,Kentucky,429871,81.8,56019,86.8,59.8,81.6,42505,59.7,340141,0.82,76.6,37.839333,-84.270018
18,19,Louisiana,374287,80.7,50315,83.9,63.0,78.1,37421,62.0,305732,0.73,65.8,31.244823,-92.145024
19,20,Maine,164176,78.5,15126,88.4,77.9,77.6,14693,68.5,131711,0.60,49.4,42.407211,-71.382437
20,21,Maryland,626992,79.4,74974,85.8,68.2,79.9,60880,63.6,561892,0.44,46.7,39.045755,-76.641271
21,22,Massachusetts,671743,82.0,64889,90.4,78.5,83.0,61953,74.3,568811,0.50,54.3,45.253783,-69.445469
22,23,Michigan,879890,80.4,102947,86.3,66.4,77.9,80347,65.0,703694,0.58,55.4,44.314844,-85.602364
23,24,Minnesota,261265,73.0,20450,88.1,69.7,75.2,19287,63.9,463924,0.43,36.6,46.729553,-94.685900
24,25,Mississippi,334251,83.4,46043,85.1,63.5,76.6,33903,57.2,264560,0.79,70.2,37.964253,-91.831833
25,26,Missouri,577944,79.4,64557,86.3,67.3,78.1,54617,62.7,469109,0.64,56.6,32.354668,-89.398528
26,27,Montana,128769,77.0,10310,81.2,66.0,67.1,12178,62.0,103019,0.69,41.1,46.879682,-110.362566
27,28,Nebraska,216981,83.4,20148,84.6,70.3,72.7,19756,62.6,177122,0.57,48.3,35.759573,-79.019300
28,29,Nevada,218612,71.6,23643,78.1,61.8,75.7,22243,55.3,185792,0.43,42.2,47.551493,-101.002012
29,30,New Hampshire,180217,77.6,16865,90.4,75.2,79.1,17739,69.5,147587,0.40,47.1,41.492537,-99.901813
30,31,New Jersey,958199,75.5,101740,85.5,66.7,84.4,85797,61.4,787803,0.57,49.6,43.193852,-71.572395
31,32,New Mexico,180688,76.2,19289,73.2,61.8,65.2,17687,57.0,147400,0.46,39.5,40.058324,-74.405661
32,33,New York,1440332,73.5,143216,86.3,70.0,82.7,127130,61.9,1222897,0.55,46.8,34.972730,-105.032363
33,34,North Carolina,903547,84.7,116516,89.0,69.2,82.0,92242,68.1,720783,0.73,49.0,38.802610,-116.419389
34,35,North Dakota,76856,83.9,7165,87.2,75.1,77.5,6742,69.4,74822,0.69,49.1,43.299428,-74.217933
35,36,Ohio,882459,79.9,103070,85.4,62.5,77.3,82954,62.4,737127,0.55,57.0,40.417287,-82.907123
36,37,Oklahoma,412648,80.0,50627,79.5,64.2,71.1,40897,55.8,334436,0.63,59.9,35.007752,-97.092877
37,38,Oregon,301683,76.4,28171,86.7,67.9,74.9,30403,61.3,253431,0.43,33.9,43.804133,-120.554201
38,39,Pennsylvania,1069125,80.3,110932,86.9,68.2,81.1,101587,65.1,901922,0.64,51.7,41.203322,-77.194525
39,41,Rhode Island,85947,80.8,8799,87.6,75.7,81.1,8086,69.1,73017,0.52,54.0,18.220833,-66.590149
40,42,South Carolina,550660,85.1,70300,87.3,66.7,81.7,58753,67.8,434703,0.69,45.6,41.580095,-71.477429
41,43,South Dakota,98709,78.4,9365,84.7,70.4,73.0,9441,66.3,95114,0.57,50.5,33.836081,-81.163725
42,44,Tennessee,585905,82.8,73625,87.5,63.8,82.4,59020,62.7,475503,0.72,59.3,43.969515,-99.901813
43,45,Texas,1777117,77.5,215445,84.1,63.6,80.7,172456,58.6,1497806,0.71,53.2,35.517491,-86.580447
51,99,United States,26937083,79.1,2919457,85.7,66.6,79.5,2544732,63.2,22488202,0.58,49.4,43.075968,-107.290284
44,46,Utah,169402,80.4,16378,86.6,68.9,72.5,15901,59.5,142323,0.41,27.9,31.968599,-99.901813
45,47,Vermont,91053,82.5,7820,88.8,71.7,69.6,8889,66.8,73544,0.48,39.4,39.320980,-111.093731
46,49,Virginia,832699,83.3,98165,87.6,70.0,82.0,83135,64.5,703266,0.53,42.8,37.431573,-78.656894
47,50,Washington,610922,78.5,56474,86.6,67.7,76.3,56238,60.0,510796,0.46,32.7,44.558803,-72.577841
48,51,West Virginia,206961,80.8,29239,84.7,59.9,78.2,20777,59.1,171837,0.90,75.0,47.751074,-120.740139
49,52,Wisconsin,474364,79.8,46596,91.0,69.7,81.6,44595,71.9,418646,0.65,45.0,43.784440,-88.787868
50,53,Wyoming,72959,72.7,6146,78.2,62.8,59.5,7201,56.0,58899,0.39,43.1,38.597626,-80.454903

In [12]:
# Lists for year columns (made in excel using the "&" formula and the fill function)

medicare_year_2011 = ["2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", 
        "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", 
        "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", 
        "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011"]

medicare_year_2012 = ["2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012",
             "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012",
             "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012",
             "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012"]

medicare_year_2013 = ["2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013",
             "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013",
             "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013",
             "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013"]

medicare_year_2014 = ["2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014",
                      "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014",
                      "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014",
                      "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014"]

medicare_year_2015 = ["2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015",
                      "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015",
                      "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015",
                      "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015"]

In [13]:
# Adding the year column into each dataframe in order to use year filters in Tableau

medicare_2011_states.insert(1, "year", medicare_year_2011, True)
medicare_2012_states.insert(1, "year", medicare_year_2012, True)
medicare_2013_states.insert(1, "year", medicare_year_2013, True)
medicare_2014_states.insert(1, "year", medicare_year_2014, True)
medicare_2015_states.insert(1, "year", medicare_year_2015, True)

In [14]:
# Stack tables together using concat

medicare_concat_1 = pd.concat([medicare_2011_states, medicare_2012_states], axis =0)
medicare_concat_2 = pd.concat([medicare_concat_1, medicare_2013_states], axis =0)
medicare_concat_3 = pd.concat([medicare_concat_2, medicare_2014_states], axis =0)
medicare_all = pd.concat([medicare_concat_3, medicare_2015_states], axis =0)
medicare_all

,state_id,year,state_name,beneficiaries_part_b,one_ambulatory_visit,diabetic_enrollees_age_65_to_75,average_diabetic_enrollees_hemoglobin_a1c_test,average_diabetic_enrollees_eye_exam,average_diabetic_enrollees_blood_lipids_test,average_female_enrollees_age_67_to_69,average_female_age_67_to_69_mammogram,beneficiaries_part_a_eligible,leg_amputations_per_1000_enrollees,discharges_ambulatory_care_sensitive_conditions_per_1000_enrollees
0,1.0,2011,Alabama,478784.0,82.5,69691.0,83.9,63.3,80.3,42267.0,62.8,501422.0,0.99,76.4
1,2.0,2011,Alaska,49648.0,70.9,5449.0,74.5,55.8,66.9,5151.0,55.3,54928.0,0.81,53.1
2,3.0,2011,Arizona,465298.0,78.2,50991.0,78.5,66.1,75.8,43614.0,64.3,501103.0,0.57,51.4
3,4.0,2011,Arkansas,327939.0,80.7,40202.0,82.5,66.1,76.2,29290.0,58.3,345431.0,0.85,77.0
4,5.0,2011,California,2238140.0,72.7,243999.0,80.6,64.1,78.0,190971.0,59.0,2378472.0,0.63,49.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,49.0,2015,Virginia,832699.0,83.3,98165.0,87.6,70.0,82.0,83135.0,64.5,703266.0,0.53,42.8
47,50.0,2015,Washington,610922.0,78.5,56474.0,86.6,67.7,76.3,56238.0,60.0,510796.0,0.46,32.7
48,51.0,2015,West Virginia,206961.0,80.8,29239.0,84.7,59.9,78.2,20777.0,59.1,171837.0,0.90,75.0
49,52.0,2015,Wisconsin,474364.0,79.8,46596.0,91.0,69.7,81.6,44595.0,71.9,418646.0,0.65,45.0
50,53.0,2015,Wyoming,72959.0,72.7,6146.0,78.2,62.8,59.5,7201.0,56.0,58899.0,0.39,43.1

In [15]:
# Export to csv

medicare_all.to_csv('../Resources\Tableau_clean\medicare_all.csv', index=False)

### Census Data

In [16]:
# Read our data into pandas

census_2011 = pd.read_csv(file6)
census_2012 = pd.read_csv(file7)
census_2013 = pd.read_csv(file8)
census_2014 = pd.read_csv(file9)
census_2015 = pd.read_csv(file10)

In [17]:
census_2011

                    Name  Population    HHI  PovertyRate
0                Alabama     4747424  42934    17.133186
1                 Alaska      700703  69014     9.292239
2                Arizona     6337373  50752    15.835820
3               Arkansas     2895928  40149    17.846507
4             California    36969200  61632    14.096818
5               Colorado     4966061  57685    12.237606
6            Connecticut     3558172  69243     9.183676
7               Delaware      890856  59317    10.866515
8   District of Columbia      593955  61835    17.144902
9                Florida    18688787  47827    14.336939
10               Georgia     9600612  49736    16.055872
11                Hawaii     1346554  67116     9.980068
12                 Idaho     1549987  46890    13.982956
13              Illinois    12790182  56576    12.825681
14               Indiana     6454254  48393    13.714211
15                  Iowa     3032266  50451    11.461264
16                Kansas     2830985  50594    12.263717
17              Kentucky     4316040  42248    17.537998
18             Louisiana     4484596  44086    17.854563
19                 Maine     1328543  47898    12.430610
20              Maryland     5736545  72419     8.761545
21         Massachusetts     6512227  65981    10.341577
22              Michigan     9920621  48669    15.306078
23             Minnesota     5278190  58476    10.707345
24           Mississippi     2956700  38718    20.895086
25              Missouri     5955802  47202    13.912736
26               Montana      982854  45324    14.234464
27              Nebraska     1813061  50695    11.679254
28                Nevada     2673396  55553    12.751684
29         New Hampshire     1315911  64664     7.723471
30            New Jersey     8753064  71180     9.198722
31            New Mexico     2037136  44631    18.570238
32              New York    19302448  56951    14.102393
33        North Carolina     9418736  46291    15.644944
34          North Dakota      666783  49415    11.831135
35                  Ohio    11525536  48071    14.352417
36              Oklahoma     3714520  44287    15.777166
37                Oregon     3801991  49850    14.475889
38          Pennsylvania    12660739  51651    12.233638
39          Rhode Island     1053959  55975    12.282641
40        South Carolina     4575864  44587    16.471316
41          South Dakota      807697  48010    13.289266
42             Tennessee     6297991  43989    16.452850
43                 Texas    24774187  50920    16.630620
44                  Utah     2715379  57783    11.200094
45               Vermont      624958  53422    10.842489
46              Virginia     7926192  63302    10.325538
47            Washington     6652845  58890    12.273080
48         West Virginia     1846372  39550    16.971824
49             Wisconsin     5664893  52374    11.679921
50               Wyoming      554697  56380     9.897295

In [18]:
# Drop extra row tallying up Puerto Rico

census_2011_states = census_2011.iloc[0:51]
census_2012_states = census_2012.iloc[0:51]
census_2013_states = census_2013.iloc[0:51]
census_2014_states = census_2014.iloc[0:51]
census_2015_states = census_2015.iloc[0:51]
census_2011_states

                    Name  Population    HHI  PovertyRate
0                Alabama     4747424  42934    17.133186
1                 Alaska      700703  69014     9.292239
2                Arizona     6337373  50752    15.835820
3               Arkansas     2895928  40149    17.846507
4             California    36969200  61632    14.096818
5               Colorado     4966061  57685    12.237606
6            Connecticut     3558172  69243     9.183676
7               Delaware      890856  59317    10.866515
8   District of Columbia      593955  61835    17.144902
9                Florida    18688787  47827    14.336939
10               Georgia     9600612  49736    16.055872
11                Hawaii     1346554  67116     9.980068
12                 Idaho     1549987  46890    13.982956
13              Illinois    12790182  56576    12.825681
14               Indiana     6454254  48393    13.714211
15                  Iowa     3032266  50451    11.461264
16                Kansas     2830985  50594    12.263717
17              Kentucky     4316040  42248    17.537998
18             Louisiana     4484596  44086    17.854563
19                 Maine     1328543  47898    12.430610
20              Maryland     5736545  72419     8.761545
21         Massachusetts     6512227  65981    10.341577
22              Michigan     9920621  48669    15.306078
23             Minnesota     5278190  58476    10.707345
24           Mississippi     2956700  38718    20.895086
25              Missouri     5955802  47202    13.912736
26               Montana      982854  45324    14.234464
27              Nebraska     1813061  50695    11.679254
28                Nevada     2673396  55553    12.751684
29         New Hampshire     1315911  64664     7.723471
30            New Jersey     8753064  71180     9.198722
31            New Mexico     2037136  44631    18.570238
32              New York    19302448  56951    14.102393
33        North Carolina     9418736  46291    15.644944
34          North Dakota      666783  49415    11.831135
35                  Ohio    11525536  48071    14.352417
36              Oklahoma     3714520  44287    15.777166
37                Oregon     3801991  49850    14.475889
38          Pennsylvania    12660739  51651    12.233638
39          Rhode Island     1053959  55975    12.282641
40        South Carolina     4575864  44587    16.471316
41          South Dakota      807697  48010    13.289266
42             Tennessee     6297991  43989    16.452850
43                 Texas    24774187  50920    16.630620
44                  Utah     2715379  57783    11.200094
45               Vermont      624958  53422    10.842489
46              Virginia     7926192  63302    10.325538
47            Washington     6652845  58890    12.273080
48         West Virginia     1846372  39550    16.971824
49             Wisconsin     5664893  52374    11.679921
50               Wyoming      554697  56380     9.897295

In [19]:
# Sort Census dataframes by state name

census_2011 = census_2011.sort_values("Name")  
census_2012 = census_2012.sort_values("Name")  
census_2013 = census_2013.sort_values("Name")  
census_2014 = census_2014.sort_values("Name")  
census_2015 = census_2015.sort_values("Name")

In [20]:
# Append latitude and longitude into Census dataframes

census_2011['Latitude'] = states['latitude']
census_2011['Longitude'] = states['longitude']
census_2012['Latitude'] = states['latitude']
census_2012['Longitude'] = states['longitude']
census_2013['Latitude'] = states['latitude']
census_2013['Longitude'] = states['longitude']
census_2014['Latitude'] = states['latitude']
census_2014['Longitude'] = states['longitude']
census_2015['Latitude'] = states['latitude']
census_2015['Longitude'] = states['longitude']

In [21]:
census_2011

,Name,Population,HHI,PovertyRate,Latitude,Longitude
0,Alabama,4747424,42934,17.133186,63.588753,-154.493062
1,Alaska,700703,69014,9.292239,32.318231,-86.902298
2,Arizona,6337373,50752,15.835820,35.201050,-91.831833
3,Arkansas,2895928,40149,17.846507,34.048928,-111.093731
4,California,36969200,61632,14.096818,36.778261,-119.417932
5,Colorado,4966061,57685,12.237606,39.550051,-105.782067
6,Connecticut,3558172,69243,9.183676,41.603221,-73.087749
7,Delaware,890856,59317,10.866515,38.905985,-77.033418
8,District of Columbia,593955,61835,17.144902,38.910832,-75.527670
9,Florida,18688787,47827,14.336939,27.664827,-81.515754
10,Georgia,9600612,49736,16.055872,32.157435,-82.907123
11,Hawaii,1346554,67116,9.980068,19.898682,-155.665857
12,Idaho,1549987,46890,13.982956,41.878003,-93.097702
13,Illinois,12790182,56576,12.825681,44.068202,-114.742041
14,Indiana,6454254,48393,13.714211,40.633125,-89.398528
15,Iowa,3032266,50451,11.461264,40.551217,-85.602364
16,Kansas,2830985,50594,12.263717,39.011902,-98.484246
17,Kentucky,4316040,42248,17.537998,37.839333,-84.270018
18,Louisiana,4484596,44086,17.854563,31.244823,-92.145024
19,Maine,1328543,47898,12.430610,42.407211,-71.382437
20,Maryland,5736545,72419,8.761545,39.045755,-76.641271
21,Massachusetts,6512227,65981,10.341577,45.253783,-69.445469
22,Michigan,9920621,48669,15.306078,44.314844,-85.602364
23,Minnesota,5278190,58476,10.707345,46.729553,-94.685900
24,Mississippi,2956700,38718,20.895086,37.964253,-91.831833
25,Missouri,5955802,47202,13.912736,32.354668,-89.398528
26,Montana,982854,45324,14.234464,46.879682,-110.362566
27,Nebraska,1813061,50695,11.679254,35.759573,-79.019300
28,Nevada,2673396,55553,12.751684,47.551493,-101.002012
29,New Hampshire,1315911,64664,7.723471,41.492537,-99.901813
30,New Jersey,8753064,71180,9.198722,43.193852,-71.572395
31,New Mexico,2037136,44631,18.570238,40.058324,-74.405661
32,New York,19302448,56951,14.102393,34.972730,-105.032363
33,North Carolina,9418736,46291,15.644944,38.802610,-116.419389
34,North Dakota,666783,49415,11.831135,43.299428,-74.217933
35,Ohio,11525536,48071,14.352417,40.417287,-82.907123
36,Oklahoma,3714520,44287,15.777166,35.007752,-97.092877
37,Oregon,3801991,49850,14.475889,43.804133,-120.554201
38,Pennsylvania,12660739,51651,12.233638,41.203322,-77.194525
39,Rhode Island,1053959,55975,12.282641,18.220833,-66.590149
40,South Carolina,4575864,44587,16.471316,41.580095,-71.477429
41,South Dakota,807697,48010,13.289266,33.836081,-81.163725
42,Tennessee,6297991,43989,16.452850,43.969515,-99.901813
43,Texas,24774187,50920,16.630620,35.517491,-86.580447
44,Utah,2715379,57783,11.200094,31.968599,-99.901813
45,Vermont,624958,53422,10.842489,39.320980,-111.093731
46,Virginia,7926192,63302,10.325538,37.431573,-78.656894
47,Washington,6652845,58890,12.273080,44.558803,-72.577841
48,West Virginia,1846372,39550,16.971824,47.751074,-120.740139
49,Wisconsin,5664893,52374,11.679921,43.784440,-88.787868
50,Wyoming,554697,56380,9.897295,38.597626,-80.454903

In [22]:
# Lists for year columns (copied from above)

census_year_2011 = ["2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", 
        "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", 
        "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", 
        "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011", "2011"]

census_year_2012 = ["2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012",
             "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012",
             "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012",
             "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012", "2012"]

census_year_2013 = ["2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013",
             "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013",
             "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013",
             "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013", "2013"]

census_year_2014 = ["2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014",
                      "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014",
                      "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014",
                      "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014", "2014"]

census_year_2015 = ["2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015",
                      "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015",
                      "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015",
                      "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015", "2015"]

In [23]:
# Adding the year column into each dataframe

census_2011_states.insert(1, "year", census_year_2011, True)
census_2012_states.insert(1, "year", census_year_2012, True)
census_2013_states.insert(1, "year", census_year_2013, True)
census_2014_states.insert(1, "year", census_year_2014, True)
census_2015_states.insert(1, "year", census_year_2015, True)

In [24]:
# Stack tables together using concat

census_concat_1 = pd.concat([census_2011_states, census_2012_states], axis =0)
census_concat_2 = pd.concat([census_concat_1, census_2013_states], axis =0)
census_concat_3 = pd.concat([census_concat_2, census_2014_states], axis =0)
census_all = pd.concat([census_concat_3, census_2015_states], axis =0)
census_all

             Name  year  Population    HHI  PovertyRate
0         Alabama  2011     4747424  42934    17.133186
1          Alaska  2011      700703  69014     9.292239
2         Arizona  2011     6337373  50752    15.835820
3        Arkansas  2011     2895928  40149    17.846507
4      California  2011    36969200  61632    14.096818
..            ...   ...         ...    ...          ...
46       Virginia  2015     8256630  65015    11.164628
47     Washington  2015     6985464  61062    13.005750
48  West Virginia  2015     1851420  41751    17.466809
49      Wisconsin  2015     5742117  53357    12.614651
50        Wyoming  2015      579679  58840    11.212240

[255 rows x 5 columns]

In [25]:
# Export to csv

census_all.to_csv('..\Resources\Tableau_clean\census_all.csv', index=False)

### Pollution Data

In [26]:
# Read our data into pandas

pollution_2011 = pd.read_csv(file12)
pollution_2012 = pd.read_csv(file13)
pollution_2013 = pd.read_csv(file14)
pollution_2014 = pd.read_csv(file15)
pollution_2015 = pd.read_csv(file16)

In [27]:
# Sort Pollution dataframes by state name

pollution_2011 = pollution_2011.sort_values("State")  
pollution_2012 = pollution_2012.sort_values("State")  
pollution_2013 = pollution_2013.sort_values("State")  
pollution_2014 = pollution_2014.sort_values("State")  
pollution_2015 = pollution_2015.sort_values("State")

In [28]:
# Sort Pollution dataframes by state name

pollution_2011_states = pollution_2011.sort_values("State")  
pollution_2012_states = pollution_2012.sort_values("State")  
pollution_2013_states = pollution_2013.sort_values("State")  
pollution_2014_states = pollution_2014.sort_values("State")  
pollution_2015_states = pollution_2015.sort_values("State")

In [29]:
pollution_2011_states.head()

,State,County,Year,Days_with_AQI,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Max_AQI,Median_AQI,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,Baldwin,2011,282,204,69,0,0,0,126,42,0,0,209,0,73,0
9,Alabama,Madison,2011,331,222,105,0,0,0,126,44,0,0,202,0,76,53
1,Alabama,Clay,2011,118,80,38,0,0,0,86,39,0,0,0,0,118,0
2,Alabama,Colbert,2011,279,214,64,0,0,0,101,42,0,0,197,0,82,0
3,Alabama,DeKalb,2011,336,257,78,0,0,0,101,40,0,0,271,0,65,0

In [30]:
# Group each year by State

In [31]:
grouped_p_2011 = pd.DataFrame({"Days_with_AQI": pollution_2011_states.groupby(["State"]).mean()["Days_with_AQI"], 
                                "Year": pollution_2011_states.groupby(["State"]).mean()["Year"],
                             "Good_Days": pollution_2011_states.groupby(["State"]).mean()["Good_Days"],
                             "Moderate_Days": pollution_2011_states.groupby(["State"]).mean()["Moderate_Days"], 
                             "Unhealthy_Days": pollution_2011_states.groupby(["State"]).mean()["Unhealthy_Days"],   
                             "Very_Unhealthy_Days": pollution_2011_states.groupby(["State"]).mean()["Very_Unhealthy_Days"], 
                             "Hazardous_Days": pollution_2011_states.groupby(["State"]).mean()["Unhealthy_Days"],
                             "Days_CO": pollution_2011_states.groupby(["State"]).mean()["Days_CO"],
                             "Days_NO2": pollution_2011_states.groupby(["State"]).mean()["Days_NO2"],
                             "Days_Ozone": pollution_2011_states.groupby(["State"]).mean()["Days_Ozone"],
                             "Days_SO2": pollution_2011_states.groupby(["State"]).mean()["Days_SO2"],
                             "Days_PM2_5": pollution_2011_states.groupby(["State"]).mean()["Days_PM2_5"],
                             "Days_PM10": pollution_2011_states.groupby(["State"]).mean()["Days_PM10"]})

In [32]:
grouped_p_2011_i = grouped_p_2011.reset_index()    
grouped_p_2011_i

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.526316,2011.0,171.789474,72.368421,0.368421,0.000000,0.368421,0.105263,0.000000,158.631579,0.157895,84.894737,4.736842
1,Alaska,274.500000,2011.0,235.250000,34.875000,0.625000,0.125000,0.625000,2.125000,0.000000,75.625000,0.000000,176.250000,20.500000
2,Arizona,320.615385,2011.0,177.153846,117.000000,2.384615,1.000000,2.384615,0.000000,3.153846,167.153846,16.538462,27.769231,106.000000
3,Arkansas,216.882353,2011.0,154.470588,59.176471,0.117647,0.000000,0.117647,0.000000,3.000000,108.764706,14.764706,90.352941,0.000000
4,California,345.648148,2011.0,193.166667,120.370370,7.018519,0.370370,7.018519,0.166667,6.907407,197.425926,0.092593,129.240741,11.814815
5,Colorado,285.156250,2011.0,190.468750,85.406250,0.406250,0.031250,0.406250,0.437500,7.875000,194.312500,0.218750,17.656250,64.656250
6,Connecticut,280.875000,2011.0,221.625000,50.750000,2.500000,0.000000,2.500000,5.625000,25.000000,190.000000,1.625000,58.625000,0.000000
7,Country Of Mexico,362.500000,2011.0,220.000000,106.500000,6.000000,2.500000,6.000000,52.000000,48.500000,204.000000,0.000000,0.000000,58.000000
8,Delaware,365.000000,2011.0,250.000000,102.000000,2.333333,0.000000,2.333333,0.000000,0.333333,271.333333,0.000000,93.333333,0.000000
9,District Of Columbia,365.000000,2011.0,135.000000,214.000000,3.000000,0.000000,3.000000,0.000000,26.000000,114.000000,1.000000,224.000000,0.000000
10,Florida,347.743590,2011.0,276.000000,67.897436,0.205128,0.000000,0.205128,0.000000,0.384615,221.205128,10.897436,106.512821,8.743590
11,Georgia,295.625000,2011.0,168.343750,118.781250,0.437500,0.000000,0.437500,0.031250,4.531250,113.312500,6.625000,169.812500,1.312500
12,Hawaii,331.000000,2011.0,208.500000,54.250000,33.750000,0.000000,33.750000,1.250000,7.000000,32.500000,104.000000,184.750000,1.500000
13,Idaho,318.176471,2011.0,274.705882,40.647059,0.352941,0.000000,0.352941,0.647059,0.588235,57.117647,31.235294,178.882353,49.705882
14,Illinois,335.461538,2011.0,257.653846,71.730769,0.769231,0.000000,0.769231,3.000000,2.115385,223.461538,45.538462,61.153846,0.192308
15,Indiana,272.476190,2011.0,179.904762,85.857143,0.404762,0.000000,0.404762,1.214286,0.880952,106.261905,57.785714,105.309524,1.023810
16,Iowa,270.150000,2011.0,180.700000,87.400000,0.650000,0.000000,0.650000,0.000000,0.300000,80.950000,5.750000,160.250000,22.900000
17,Kansas,262.800000,2011.0,195.533333,61.066667,0.066667,0.000000,0.066667,0.000000,8.000000,172.466667,7.666667,42.600000,32.066667
18,Kentucky,301.200000,2011.0,214.666667,81.000000,0.433333,0.000000,0.433333,0.000000,2.766667,188.800000,15.233333,92.200000,2.200000
19,Louisiana,338.454545,2011.0,227.590909,97.818182,2.045455,0.000000,2.045455,0.000000,2.136364,209.772727,6.818182,119.272727,0.454545
20,Maine,273.916667,2011.0,247.500000,25.083333,0.250000,0.000000,0.250000,0.000000,1.583333,210.333333,0.083333,58.333333,3.583333
21,Maryland,304.066667,2011.0,190.400000,98.333333,2.933333,0.200000,2.933333,0.000000,7.000000,181.666667,0.133333,114.866667,0.400000
22,Massachusetts,329.750000,2011.0,244.166667,80.750000,0.583333,0.083333,0.583333,0.083333,9.166667,175.333333,2.250000,142.916667,0.000000
23,Michigan,245.071429,2011.0,192.214286,46.321429,0.785714,0.000000,0.785714,0.000000,1.464286,178.285714,1.285714,63.892857,0.142857
24,Minnesota,290.666667,2011.0,238.000000,51.523810,0.047619,0.000000,0.047619,0.952381,3.047619,119.285714,8.380952,154.619048,4.380952
25,Mississippi,292.307692,2011.0,195.615385,94.153846,0.000000,0.000000,0.000000,0.000000,5.307692,124.769231,1.076923,161.153846,0.000000
26,Missouri,284.772727,2011.0,180.545455,91.318182,0.954545,0.000000,0.954545,0.000000,2.545455,165.772727,17.136364,85.227273,14.090909
27,Montana,285.611111,2011.0,231.000000,50.111111,0.500000,0.000000,0.500000,0.888889,1.500000,65.166667,9.833333,173.944444,34.277778
28,Nebraska,218.727273,2011.0,174.818182,43.363636,0.000000,0.000000,0.000000,10.181818,0.000000,66.727273,2.454545,98.090909,41.272727
29,Nevada,299.700000,2011.0,235.200000,58.100000,0.200000,0.000000,0.200000,33.100000,5.400000,148.700000,0.000000,16.900000,95.600000
30,New Hampshire,341.714286,2011.0,259.428571,72.142857,1.285714,0.000000,1.285714,0.714286,0.000000,232.285714,34.428571,74.285714,0.000000
31,New Jersey,349.937500,2011.0,248.437500,88.750000,1.875000,0.000000,1.875000,3.125000,29.375000,190.062500,4.312500,122.125000,0.937500
32,New Mexico,273.833333,2011.0,197.055556,70.833333,0.333333,0.111111,0.333333,0.000000,5.000000,156.611111,1.388889,76.277778,34.555556
33,New York,347.323529,2011.0,282.764706,60.676471,0.558824,0.029412,0.558824,0.294118,9.529412,239.647059,3.441176,94.411765,0.000000
34,North Carolina,285.978261,2011.0,193.630435,87.347826,0.326087,0.000000,0.326087,0.000000,0.369565,146.826087,13.652174,125.130435,0.000000
35,North Dakota,353.555556,2011.0,322.666667,29.777778,0.000000,0.111111,0.000000,0.000000,4.000000,219.444444,50.888889,72.777778,6.444444
36,Ohio,316.441860,2011.0,211.488372,93.162791,0.697674,0.000000,0.697674,0.348837,2.418605,134.116279,55.837209,117.255814,6.465116
37,Oklahoma,331.304348,2011.0,200.956522,110.043478,0.956522,0.000000,0.956522,0.000000,3.652174,240.565217,7.826087,63.782609,15.478261
38,Oregon,328.360000,2011.0,266.840000,57.680000,0.440000,0.000000,0.440000,0.000000,0.120000,52.840000,0.000000,275.200000,0.200000
39,Pennsylvania,346.552632,2011.0,222.500000,115.105263,0.684211,0.000000,0.684211,0.105263,5.552632,177.263158,15.710526,142.315789,5.605263
40,Puerto Rico,228.230769,2011.0,223.307692,4.923077,0.000000,0.000000,0.000000,26.000000,0.000000,37.000000,68.846154,25.461538,70.923077
41,Rhode Island,314.666667,2011.0,243.666667,64.666667,0.000000,0.000000,0.000000,0.000000,3.666667,211.666667,0.000000,99.333333,0.000000
42,South Carolina,299.700000,2011.0,209.200000,86.300000,0.200000,0.000000,0.200000,0.000000,1.250000,185.800000,5.700000,88.150000,18.800000
43,South Dakota,334.000000,2011.0,296.222222,37.444444,0.000000,0.000000,0.000000,0.000000,9.666667,190.666667,0.000000,79.444444,54.222222
44,Tennessee,296.750000,2011.0,206.041667,81.166667,0.541667,0.000000,0.541667,0.041667,24.166667,180.208333,25.500000,41.291667,25.541667
45,Texas,334.955556,2011.0,227.422222,93.377778,1.933333,0.044444,1.933333,0.000000,3.888889,201.711111,1.666667,126.377778,1.311111
46,Utah,310.200000,2011.0,200.466667,99.466667,2.200000,0.600000,2.200000,0.000000,23.733333,219.866667,0.200000,65.133333,1.266667
47,Vermont,274.000000,2011.0,205.500000,66.250000,0.000000,0.000000,0.000000,1.500000,2.750000,107.500000,2.000000,160.250000,0.000000
48,Virgin Islands,240.500000,2011.0,218.000000,19.500000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,169.500000,63.500000,7.500000
49,Virginia,252.631579,2011.0,198.973684,49.842105,0.421053,0.000000,0.421053,0.368421,39.789474,127.500000,4.026316,69.789474,11.157895
50,Washington,348.133333,2011.0,301.366667,44.766667,0.433333,0.000000,0.433333,0.266667,1.066667,45.766667,0.066667,291.933333,9.033333
51,West Virginia,280.562500,2011.0,210.500000,65.937500,0.500000,0.000000,0.500000,0.000000,0.000000,126.875000,67.250000,81.125000,5.312500
52,Wisconsin,246.233333,2011.0,194.266667,47.200000,0.400000,0.033333,0.400000,0.000000,0.666667,175.500000,8.533333,59.233333,2.300000
53,Wyoming,298.000000,2011.0,235.473684,60.157895,0.263158,0.157895,0.263158,0.210526,3.210526,176.315789,21.052632,30.526316,66.684211

In [33]:
grouped_p_2012 = pd.DataFrame({"Days_with_AQI": pollution_2012_states.groupby(["State"]).mean()["Days_with_AQI"], 
                                "Year": pollution_2012_states.groupby(["State"]).mean()["Year"],
                             "Good_Days": pollution_2012_states.groupby(["State"]).mean()["Good_Days"],
                             "Moderate_Days": pollution_2012_states.groupby(["State"]).mean()["Moderate_Days"], 
                             "Unhealthy_Days": pollution_2012_states.groupby(["State"]).mean()["Unhealthy_Days"],   
                             "Very_Unhealthy_Days": pollution_2012_states.groupby(["State"]).mean()["Very_Unhealthy_Days"], 
                             "Hazardous_Days": pollution_2012_states.groupby(["State"]).mean()["Unhealthy_Days"],
                             "Days_CO": pollution_2012_states.groupby(["State"]).mean()["Days_CO"],
                             "Days_NO2": pollution_2012_states.groupby(["State"]).mean()["Days_NO2"],
                             "Days_Ozone": pollution_2012_states.groupby(["State"]).mean()["Days_Ozone"],
                             "Days_SO2": pollution_2012_states.groupby(["State"]).mean()["Days_SO2"],
                             "Days_PM2_5": pollution_2012_states.groupby(["State"]).mean()["Days_PM2_5"],
                             "Days_PM10": pollution_2012_states.groupby(["State"]).mean()["Days_PM10"]})

In [34]:
grouped_p_2012_i = grouped_p_2012.reset_index()   
grouped_p_2012_i

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,263.588235,2012.0,201.000000,58.823529,0.235294,0.000000,0.235294,0.000000,0.000000,174.529412,0.411765,85.117647,3.529412
1,Alaska,301.250000,2012.0,258.625000,36.625000,3.125000,0.250000,3.125000,1.375000,0.000000,95.250000,0.875000,152.750000,51.000000
2,Arizona,336.538462,2012.0,185.846154,120.076923,3.076923,0.307692,3.076923,0.000000,3.000000,179.307692,19.307692,22.307692,112.615385
3,Arkansas,225.071429,2012.0,164.571429,56.500000,0.357143,0.000000,0.357143,0.000000,2.642857,123.285714,18.142857,81.000000,0.000000
4,California,349.611111,2012.0,202.314815,113.833333,6.833333,0.370370,6.833333,0.037037,6.759259,219.462963,0.092593,110.722222,12.537037
5,Colorado,292.193548,2012.0,198.032258,81.354839,0.870968,0.032258,0.870968,0.064516,8.516129,203.161290,0.419355,15.451613,64.580645
6,Connecticut,314.750000,2012.0,222.750000,75.875000,3.250000,0.000000,3.250000,0.125000,3.625000,193.250000,0.125000,117.500000,0.125000
7,Country Of Mexico,366.000000,2012.0,271.000000,67.000000,5.500000,1.000000,5.500000,30.500000,55.500000,214.500000,0.000000,0.000000,65.500000
8,Delaware,358.000000,2012.0,237.333333,101.000000,3.333333,0.000000,3.333333,0.000000,2.000000,254.333333,1.000000,100.666667,0.000000
9,District Of Columbia,366.000000,2012.0,127.000000,211.000000,4.000000,0.000000,4.000000,0.000000,22.000000,139.000000,0.000000,205.000000,0.000000
10,Florida,357.410256,2012.0,305.051282,50.410256,0.179487,0.000000,0.179487,0.000000,0.333333,239.820513,14.846154,93.256410,9.153846
11,Georgia,296.718750,2012.0,197.687500,94.875000,0.593750,0.031250,0.593750,0.031250,4.125000,113.406250,5.812500,172.062500,1.281250
12,Hawaii,361.000000,2012.0,251.500000,24.500000,55.250000,0.750000,55.250000,3.250000,1.500000,32.250000,98.500000,224.250000,1.250000
13,Idaho,343.133333,2012.0,282.733333,53.000000,3.000000,0.866667,3.000000,0.400000,1.666667,37.333333,33.600000,211.533333,58.600000
14,Illinois,335.346154,2012.0,245.076923,75.000000,1.807692,0.076923,1.807692,0.115385,4.192308,240.423077,44.346154,45.846154,0.423077
15,Indiana,275.000000,2012.0,181.309524,82.595238,0.904762,0.142857,0.904762,0.523810,0.547619,113.904762,61.452381,97.238095,1.333333
16,Iowa,286.842105,2012.0,185.684211,96.368421,0.368421,0.000000,0.368421,0.000000,0.526316,95.421053,10.684211,155.526316,24.684211
17,Kansas,296.076923,2012.0,218.307692,63.538462,0.923077,0.000000,0.923077,0.153846,6.153846,211.153846,0.846154,37.230769,40.538462
18,Kentucky,305.586207,2012.0,214.620690,77.862069,1.241379,0.137931,1.241379,0.034483,2.827586,210.793103,13.206897,76.172414,2.551724
19,Louisiana,339.045455,2012.0,240.000000,93.272727,0.500000,0.000000,0.500000,0.000000,2.363636,209.954545,5.409091,120.863636,0.454545
20,Maine,299.272727,2012.0,276.818182,21.636364,0.000000,0.000000,0.000000,0.000000,10.636364,236.909091,1.363636,45.545455,4.818182
21,Maryland,313.200000,2012.0,196.066667,100.866667,2.800000,0.266667,2.800000,0.400000,6.533333,200.266667,0.066667,105.733333,0.200000
22,Massachusetts,325.250000,2012.0,251.416667,67.083333,0.666667,0.000000,0.666667,0.000000,8.166667,182.333333,3.250000,131.333333,0.166667
23,Michigan,256.392857,2012.0,181.714286,56.035714,2.035714,0.214286,2.035714,0.000000,1.357143,181.071429,12.500000,59.821429,1.642857
24,Minnesota,297.285714,2012.0,243.952381,52.333333,0.047619,0.000000,0.047619,0.619048,5.714286,132.190476,2.523810,149.714286,6.523810
25,Mississippi,312.272727,2012.0,231.454545,77.090909,0.181818,0.000000,0.181818,0.000000,9.909091,141.909091,1.272727,159.181818,0.000000
26,Missouri,291.136364,2012.0,174.045455,94.545455,2.681818,0.000000,2.681818,0.000000,1.590909,153.090909,28.409091,91.681818,16.363636
27,Montana,278.789474,2012.0,212.315789,59.631579,2.421053,0.210526,2.421053,0.052632,2.157895,71.000000,9.842105,176.368421,19.368421
28,Nebraska,221.454545,2012.0,164.272727,54.181818,0.090909,0.000000,0.090909,2.181818,0.000000,75.272727,2.636364,90.636364,50.727273
29,Nevada,258.000000,2012.0,173.600000,74.500000,0.600000,0.000000,0.600000,9.200000,2.900000,148.200000,0.000000,20.900000,76.800000
30,New Hampshire,343.571429,2012.0,283.142857,57.714286,0.000000,0.000000,0.000000,0.142857,0.000000,261.571429,18.571429,63.285714,0.000000
31,New Jersey,337.250000,2012.0,243.812500,80.375000,1.375000,0.000000,1.375000,0.062500,25.062500,203.812500,1.187500,106.625000,0.500000
32,New Mexico,272.388889,2012.0,200.833333,66.111111,0.166667,0.166667,0.166667,0.000000,2.888889,172.055556,0.055556,70.666667,26.722222
33,New York,351.060606,2012.0,287.848485,57.000000,0.393939,0.000000,0.393939,0.242424,7.454545,254.030303,6.030303,83.303030,0.000000
34,North Carolina,286.543478,2012.0,223.152174,59.978261,0.434783,0.043478,0.434783,0.000000,0.391304,151.521739,8.413043,126.217391,0.000000
35,North Dakota,365.777778,2012.0,320.000000,44.333333,0.444444,0.000000,0.444444,0.000000,2.111111,235.333333,46.111111,75.333333,6.888889
36,Ohio,318.071429,2012.0,205.476190,98.047619,1.666667,0.071429,1.666667,1.047619,0.047619,145.738095,51.523810,111.952381,7.761905
37,Oklahoma,332.545455,2012.0,217.681818,99.318182,1.045455,0.045455,1.045455,0.000000,3.318182,227.045455,14.500000,72.454545,15.227273
38,Oregon,344.583333,2012.0,288.458333,53.375000,0.583333,0.041667,0.583333,0.000000,0.291667,52.583333,0.000000,291.625000,0.083333
39,Pennsylvania,355.842105,2012.0,224.921053,117.684211,1.105263,0.000000,1.105263,0.078947,1.973684,210.368421,13.473684,126.947368,3.000000
40,Puerto Rico,262.153846,2012.0,246.000000,16.153846,0.000000,0.000000,0.000000,39.769231,15.384615,30.538462,46.230769,51.846154,78.384615
41,Rhode Island,342.666667,2012.0,270.000000,63.333333,1.000000,0.000000,1.000000,0.000000,1.000000,217.333333,0.666667,123.666667,0.000000
42,South Carolina,280.210526,2012.0,223.578947,55.315789,0.105263,0.000000,0.105263,0.210526,2.157895,151.631579,11.368421,93.000000,21.842105
43,South Dakota,337.777778,2012.0,254.888889,81.111111,0.111111,0.000000,0.111111,0.000000,10.444444,195.666667,0.000000,97.000000,34.666667
44,Tennessee,285.304348,2012.0,203.217391,71.652174,1.173913,0.130435,1.173913,0.086957,19.478261,183.652174,19.130435,43.260870,19.695652
45,Texas,342.372093,2012.0,249.860465,82.837209,1.093023,0.232558,1.093023,0.000000,2.860465,205.000000,1.000000,132.279070,1.232558
46,Utah,337.666667,2012.0,211.600000,117.333333,0.333333,0.000000,0.333333,0.000000,22.866667,252.066667,0.066667,60.333333,2.333333
47,Vermont,302.750000,2012.0,254.500000,47.000000,0.000000,0.000000,0.000000,0.750000,9.750000,147.500000,0.250000,144.500000,0.000000
48,Virgin Islands,242.500000,2012.0,230.500000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,165.500000,77.000000,0.000000
49,Virginia,253.236842,2012.0,207.631579,41.842105,0.421053,0.026316,0.421053,0.473684,40.789474,133.763158,2.026316,65.236842,10.947368
50,Washington,358.862069,2012.0,306.620690,48.862069,1.275862,0.068966,1.275862,0.068966,2.275862,42.827586,0.000000,309.758621,3.931034
51,West Virginia,289.333333,2012.0,213.666667,70.666667,0.200000,0.000000,0.200000,0.000000,0.000000,145.333333,51.266667,86.200000,6.533333
52,Wisconsin,256.531250,2012.0,186.093750,58.062500,1.937500,0.000000,1.937500,0.000000,0.437500,163.500000,12.500000,74.281250,5.812500
53,Wyoming,308.421053,2012.0,223.052632,80.947368,0.631579,0.052632,0.631579,0.052632,5.684211,182.210526,20.368421,27.736842,72.368421

In [35]:
grouped_p_2013 = pd.DataFrame({"Days_with_AQI": pollution_2013_states.groupby(["State"]).mean()["Days_with_AQI"], 
                                "Year": pollution_2013_states.groupby(["State"]).mean()["Year"],
                             "Good_Days": pollution_2013_states.groupby(["State"]).mean()["Good_Days"],
                             "Moderate_Days": pollution_2013_states.groupby(["State"]).mean()["Moderate_Days"], 
                             "Unhealthy_Days": pollution_2013_states.groupby(["State"]).mean()["Unhealthy_Days"],   
                             "Very_Unhealthy_Days": pollution_2013_states.groupby(["State"]).mean()["Very_Unhealthy_Days"], 
                             "Hazardous_Days": pollution_2013_states.groupby(["State"]).mean()["Unhealthy_Days"],
                             "Days_CO": pollution_2013_states.groupby(["State"]).mean()["Days_CO"],
                             "Days_NO2": pollution_2013_states.groupby(["State"]).mean()["Days_NO2"],
                             "Days_Ozone": pollution_2013_states.groupby(["State"]).mean()["Days_Ozone"],
                             "Days_SO2": pollution_2013_states.groupby(["State"]).mean()["Days_SO2"],
                             "Days_PM2_5": pollution_2013_states.groupby(["State"]).mean()["Days_PM2_5"],
                             "Days_PM10": pollution_2013_states.groupby(["State"]).mean()["Days_PM10"]})

In [36]:
grouped_p_2013_i = grouped_p_2013.reset_index()  
grouped_p_2013_i

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,265.166667,2013.0,224.888889,40.111111,0.000000,0.000000,0.000000,0.000000,0.055556,173.166667,4.666667,84.055556,3.222222
1,Alaska,284.250000,2013.0,244.000000,31.875000,3.625000,0.000000,3.625000,2.500000,0.000000,52.750000,0.125000,176.625000,52.250000
2,Arizona,346.615385,2013.0,208.692308,116.615385,3.307692,0.615385,3.307692,0.000000,1.769231,180.307692,18.384615,31.076923,115.076923
3,Arkansas,268.636364,2013.0,215.090909,53.090909,0.000000,0.000000,0.000000,0.000000,2.727273,155.545455,21.818182,88.545455,0.000000
4,California,346.185185,2013.0,190.944444,127.148148,5.000000,0.203704,5.000000,0.203704,5.240741,193.796296,0.166667,128.333333,18.444444
5,Colorado,304.333333,2013.0,215.833333,80.733333,0.600000,0.100000,0.600000,0.100000,8.333333,219.333333,1.033333,17.400000,58.133333
6,Connecticut,315.000000,2013.0,213.375000,91.750000,1.875000,0.000000,1.875000,0.000000,5.750000,175.250000,0.125000,133.875000,0.000000
7,Country Of Mexico,363.500000,2013.0,289.500000,45.500000,6.500000,3.500000,6.500000,61.500000,0.000000,227.000000,0.000000,0.000000,75.000000
8,Delaware,362.333333,2013.0,264.666667,94.000000,0.000000,0.000000,0.000000,0.000000,2.000000,229.666667,0.333333,130.333333,0.000000
9,District Of Columbia,365.000000,2013.0,203.000000,161.000000,0.000000,0.000000,0.000000,0.000000,26.000000,129.000000,0.000000,210.000000,0.000000
10,Florida,354.289474,2013.0,311.315789,42.105263,0.000000,0.026316,0.000000,0.000000,0.342105,225.000000,5.552632,113.605263,9.789474
11,Georgia,297.500000,2013.0,226.968750,69.281250,0.031250,0.000000,0.031250,0.031250,4.343750,109.968750,3.625000,179.468750,0.062500
12,Hawaii,364.250000,2013.0,260.500000,27.750000,39.750000,0.250000,39.750000,1.250000,15.750000,35.250000,91.500000,219.750000,0.750000
13,Idaho,282.714286,2013.0,231.071429,45.285714,1.500000,0.000000,1.500000,0.142857,5.928571,38.357143,33.214286,157.142857,47.928571
14,Illinois,328.346154,2013.0,270.000000,55.769231,0.230769,0.000000,0.230769,0.076923,3.000000,226.884615,47.384615,50.153846,0.846154
15,Indiana,282.928571,2013.0,209.571429,71.142857,0.119048,0.000000,0.119048,0.333333,2.452381,114.119048,63.452381,101.547619,1.023810
16,Iowa,291.894737,2013.0,205.947368,82.000000,0.210526,0.000000,0.210526,0.000000,0.473684,89.789474,18.473684,159.684211,23.473684
17,Kansas,277.615385,2013.0,231.384615,45.307692,0.000000,0.000000,0.000000,0.153846,3.615385,188.615385,0.923077,44.846154,39.461538
18,Kentucky,308.724138,2013.0,256.931034,51.068966,0.000000,0.000000,0.000000,0.000000,4.034483,197.241379,13.965517,90.793103,2.689655
19,Louisiana,340.818182,2013.0,265.363636,72.636364,0.272727,0.000000,0.272727,0.000000,2.772727,208.727273,3.500000,125.545455,0.272727
20,Maine,306.636364,2013.0,278.181818,26.272727,0.000000,0.000000,0.000000,0.000000,12.545455,240.545455,0.545455,50.636364,2.363636
21,Maryland,312.533333,2013.0,232.800000,76.933333,0.000000,0.000000,0.000000,0.000000,5.733333,194.333333,0.133333,112.200000,0.133333
22,Massachusetts,341.500000,2013.0,272.250000,65.250000,0.083333,0.000000,0.083333,0.000000,4.333333,205.166667,1.500000,130.083333,0.416667
23,Michigan,264.928571,2013.0,211.250000,51.392857,0.035714,0.000000,0.035714,0.000000,1.178571,178.964286,20.357143,63.642857,0.785714
24,Minnesota,305.800000,2013.0,256.050000,49.450000,0.000000,0.000000,0.000000,0.050000,7.850000,138.550000,0.250000,151.000000,8.100000
25,Mississippi,312.200000,2013.0,266.000000,45.600000,0.000000,0.000000,0.000000,0.000000,10.400000,193.300000,2.600000,105.900000,0.000000
26,Missouri,294.727273,2013.0,213.636364,76.181818,0.181818,0.000000,0.181818,0.000000,2.363636,154.909091,28.000000,99.181818,10.272727
27,Montana,299.315789,2013.0,252.842105,43.789474,0.368421,0.000000,0.368421,0.000000,0.894737,106.421053,11.052632,161.684211,19.263158
28,Nebraska,205.363636,2013.0,172.545455,32.181818,0.000000,0.000000,0.000000,0.000000,0.000000,64.000000,1.909091,95.636364,43.818182
29,Nevada,289.500000,2013.0,202.200000,75.800000,2.600000,0.700000,2.600000,0.000000,0.800000,141.400000,0.000000,59.100000,88.200000
30,New Hampshire,343.142857,2013.0,284.857143,57.000000,0.000000,0.000000,0.000000,0.000000,0.000000,247.714286,18.142857,77.285714,0.000000
31,New Jersey,338.812500,2013.0,262.625000,72.937500,0.187500,0.000000,0.187500,0.062500,28.125000,209.312500,1.375000,99.812500,0.125000
32,New Mexico,275.555556,2013.0,205.444444,65.166667,0.722222,0.111111,0.722222,0.000000,2.555556,189.333333,1.444444,64.388889,17.833333
33,New York,356.551724,2013.0,304.586207,50.448276,0.103448,0.000000,0.103448,0.793103,9.965517,244.551724,3.413793,97.827586,0.000000
34,North Carolina,286.638298,2013.0,241.127660,45.191489,0.021277,0.000000,0.021277,0.000000,0.340426,142.340426,11.489362,132.319149,0.148936
35,North Dakota,363.444444,2013.0,320.777778,40.555556,0.888889,0.000000,0.888889,0.000000,3.444444,275.888889,10.444444,64.666667,9.000000
36,Ohio,315.439024,2013.0,235.975610,76.878049,0.073171,0.000000,0.073171,0.756098,0.414634,135.756098,44.902439,126.024390,7.585366
37,Oklahoma,306.695652,2013.0,228.652174,74.565217,0.000000,0.000000,0.000000,0.000000,3.695652,210.521739,3.391304,73.000000,16.086957
38,Oregon,345.250000,2013.0,264.750000,72.541667,1.916667,0.208333,1.916667,0.000000,0.291667,50.416667,0.000000,294.500000,0.041667
39,Pennsylvania,360.461538,2013.0,252.205128,103.435897,0.102564,0.000000,0.102564,0.025641,2.205128,214.256410,13.333333,128.538462,2.102564
40,Puerto Rico,253.076923,2013.0,247.769231,4.461538,0.384615,0.000000,0.384615,47.615385,0.000000,27.000000,35.846154,47.692308,94.923077
41,Rhode Island,362.333333,2013.0,291.333333,64.000000,0.333333,0.000000,0.333333,0.000000,1.333333,208.333333,0.000000,152.333333,0.333333
42,South Carolina,296.210526,2013.0,255.315789,40.789474,0.000000,0.000000,0.000000,0.052632,3.157895,149.631579,14.526316,108.789474,20.052632
43,South Dakota,335.444444,2013.0,273.666667,61.666667,0.000000,0.000000,0.000000,0.000000,2.666667,187.000000,0.111111,116.000000,29.666667
44,Tennessee,268.640000,2013.0,215.920000,52.080000,0.000000,0.000000,0.000000,0.080000,4.280000,150.360000,5.520000,93.640000,14.760000
45,Texas,344.162791,2013.0,263.046512,74.976744,0.441860,0.000000,0.441860,0.046512,3.372093,205.930233,1.325581,132.418605,1.069767
46,Utah,331.266667,2013.0,208.000000,100.800000,6.133333,1.600000,6.133333,0.000000,21.666667,238.066667,0.666667,70.200000,0.666667
47,Vermont,302.250000,2013.0,253.750000,47.250000,0.000000,0.000000,0.000000,0.000000,4.000000,136.000000,0.250000,162.000000,0.000000
48,Virgin Islands,96.000000,2013.0,86.500000,9.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,28.000000,60.500000,7.500000
49,Virginia,248.944444,2013.0,221.583333,26.972222,0.000000,0.000000,0.000000,0.777778,32.750000,136.305556,2.750000,67.250000,9.111111
50,Washington,346.620690,2013.0,285.344828,59.172414,0.275862,0.000000,0.275862,0.103448,0.103448,41.586207,0.000000,299.379310,5.448276
51,West Virginia,286.333333,2013.0,240.266667,45.333333,0.000000,0.000000,0.000000,0.066667,0.000000,140.466667,41.400000,94.800000,9.600000
52,Wisconsin,253.969697,2013.0,197.484848,53.939394,0.000000,0.030303,0.000000,0.000000,0.242424,152.333333,12.363636,82.151515,6.878788
53,Wyoming,319.000000,2013.0,258.000000,60.000000,0.055556,0.000000,0.055556,0.000000,3.833333,246.888889,3.666667,20.388889,44.222222

In [37]:
grouped_p_2014 = pd.DataFrame({"Days_with_AQI": pollution_2014_states.groupby(["State"]).mean()["Days_with_AQI"], 
                                "Year": pollution_2014_states.groupby(["State"]).mean()["Year"],
                             "Good_Days": pollution_2014_states.groupby(["State"]).mean()["Good_Days"],
                             "Moderate_Days": pollution_2014_states.groupby(["State"]).mean()["Moderate_Days"], 
                             "Unhealthy_Days": pollution_2014_states.groupby(["State"]).mean()["Unhealthy_Days"],   
                             "Very_Unhealthy_Days": pollution_2014_states.groupby(["State"]).mean()["Very_Unhealthy_Days"], 
                             "Hazardous_Days": pollution_2014_states.groupby(["State"]).mean()["Unhealthy_Days"],
                             "Days_CO": pollution_2014_states.groupby(["State"]).mean()["Days_CO"],
                             "Days_NO2": pollution_2014_states.groupby(["State"]).mean()["Days_NO2"],
                             "Days_Ozone": pollution_2014_states.groupby(["State"]).mean()["Days_Ozone"],
                             "Days_SO2": pollution_2014_states.groupby(["State"]).mean()["Days_SO2"],
                             "Days_PM2_5": pollution_2014_states.groupby(["State"]).mean()["Days_PM2_5"],
                             "Days_PM10": pollution_2014_states.groupby(["State"]).mean()["Days_PM10"]})

In [38]:
grouped_p_2014_i = grouped_p_2014.reset_index()  
grouped_p_2014_i

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,260.444444,2014.0,213.444444,46.111111,0.000000,0.000000,0.000000,0.000000,0.388889,173.055556,0.111111,83.611111,3.277778
1,Alaska,274.125000,2014.0,218.125000,43.625000,6.250000,0.250000,6.250000,1.125000,2.000000,68.125000,0.250000,163.875000,38.750000
2,Arizona,357.307692,2014.0,217.076923,115.846154,3.538462,0.461538,3.538462,0.000000,1.692308,180.307692,19.538462,34.307692,121.461538
3,Arkansas,272.363636,2014.0,230.272727,41.818182,0.000000,0.000000,0.000000,0.000000,2.909091,157.818182,22.545455,89.090909,0.000000
4,California,344.444444,2014.0,193.759259,121.074074,5.388889,0.185185,5.388889,0.000000,5.000000,207.444444,0.018519,117.833333,14.148148
5,Colorado,302.233333,2014.0,234.800000,64.300000,0.233333,0.033333,0.233333,0.033333,7.500000,214.866667,1.066667,19.400000,59.366667
6,Connecticut,316.125000,2014.0,235.500000,73.625000,0.375000,0.000000,0.375000,0.000000,6.000000,202.375000,0.000000,107.750000,0.000000
7,Country Of Mexico,132.500000,2014.0,110.500000,15.500000,2.500000,0.000000,2.500000,30.000000,0.000000,77.000000,0.000000,0.000000,25.500000
8,Delaware,364.666667,2014.0,253.666667,106.333333,0.666667,0.000000,0.666667,0.000000,2.333333,218.333333,0.333333,143.666667,0.000000
9,District Of Columbia,365.000000,2014.0,225.000000,136.000000,0.000000,0.000000,0.000000,0.000000,19.000000,181.000000,0.000000,165.000000,0.000000
10,Florida,357.538462,2014.0,305.461538,50.794872,0.051282,0.000000,0.051282,0.000000,0.897436,237.794872,12.564103,98.871795,7.410256
11,Georgia,294.437500,2014.0,210.125000,82.875000,0.031250,0.000000,0.031250,0.031250,4.843750,104.437500,4.125000,181.000000,0.000000
12,Hawaii,350.750000,2014.0,258.000000,25.000000,32.500000,0.250000,32.500000,0.000000,9.250000,57.250000,93.000000,187.250000,4.000000
13,Idaho,332.545455,2014.0,282.545455,45.363636,0.454545,0.000000,0.454545,0.090909,6.000000,55.000000,45.545455,161.272727,64.636364
14,Illinois,327.538462,2014.0,267.038462,57.807692,0.153846,0.000000,0.153846,0.000000,2.769231,212.307692,53.153846,57.615385,1.692308
15,Indiana,279.155556,2014.0,202.422222,73.266667,0.155556,0.000000,0.155556,0.022222,2.822222,102.355556,59.333333,113.800000,0.822222
16,Iowa,292.631579,2014.0,208.157895,80.210526,0.315789,0.000000,0.315789,0.000000,1.578947,83.526316,22.105263,159.842105,25.578947
17,Kansas,285.666667,2014.0,237.750000,46.750000,0.083333,0.000000,0.083333,0.000000,4.000000,193.583333,1.416667,46.250000,40.416667
18,Kentucky,305.551724,2014.0,246.482759,57.620690,0.034483,0.000000,0.034483,0.034483,4.931034,198.379310,14.551724,85.724138,1.931034
19,Louisiana,335.136364,2014.0,260.136364,72.363636,0.090909,0.000000,0.090909,0.000000,4.772727,198.136364,2.318182,129.636364,0.272727
20,Maine,306.181818,2014.0,279.000000,26.636364,0.000000,0.000000,0.000000,0.272727,5.636364,229.000000,5.636364,62.090909,3.545455
21,Maryland,310.625000,2014.0,228.750000,80.437500,0.000000,0.000000,0.000000,0.062500,6.687500,185.437500,0.312500,118.125000,0.000000
22,Massachusetts,361.384615,2014.0,296.769231,64.307692,0.000000,0.000000,0.000000,0.000000,5.307692,232.153846,0.076923,123.384615,0.461538
23,Michigan,282.285714,2014.0,220.928571,58.607143,0.035714,0.000000,0.035714,0.000000,0.428571,157.214286,12.214286,111.392857,1.035714
24,Minnesota,313.047619,2014.0,268.952381,43.809524,0.000000,0.000000,0.000000,0.000000,8.380952,127.142857,0.428571,168.904762,8.190476
25,Mississippi,307.600000,2014.0,251.400000,54.500000,0.100000,0.000000,0.100000,0.000000,9.800000,182.100000,3.200000,112.500000,0.000000
26,Missouri,293.590909,2014.0,218.000000,71.363636,0.000000,0.000000,0.000000,0.000000,3.409091,151.727273,22.136364,103.863636,12.454545
27,Montana,307.000000,2014.0,259.105263,45.263158,0.157895,0.000000,0.157895,0.000000,0.947368,105.263158,9.631579,164.000000,27.157895
28,Nebraska,201.363636,2014.0,175.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,65.363636,1.909091,94.090909,40.000000
29,Nevada,327.888889,2014.0,235.555556,87.333333,0.666667,0.000000,0.666667,0.000000,1.000000,176.555556,0.000000,81.555556,68.777778
30,New Hampshire,343.285714,2014.0,291.714286,50.428571,0.000000,0.000000,0.000000,0.000000,0.000000,248.571429,10.571429,84.142857,0.000000
31,New Jersey,340.312500,2014.0,271.562500,65.437500,0.125000,0.000000,0.125000,0.187500,39.375000,209.875000,1.875000,88.812500,0.187500
32,New Mexico,286.352941,2014.0,229.411765,55.058824,0.294118,0.176471,0.294118,0.000000,3.647059,200.000000,3.294118,65.117647,14.294118
33,New York,357.103448,2014.0,312.379310,43.793103,0.068966,0.000000,0.068966,0.241379,7.689655,243.655172,4.413793,101.103448,0.000000
34,North Carolina,292.340426,2014.0,233.978723,58.063830,0.000000,0.000000,0.000000,0.000000,0.553191,151.446809,13.702128,126.595745,0.042553
35,North Dakota,364.555556,2014.0,336.888889,25.555556,0.222222,0.111111,0.222222,0.000000,3.111111,287.555556,8.444444,55.222222,10.222222
36,Ohio,315.951220,2014.0,237.097561,75.926829,0.097561,0.000000,0.097561,0.804878,1.536585,140.292683,45.878049,120.073171,7.365854
37,Oklahoma,336.454545,2014.0,262.772727,72.363636,0.045455,0.000000,0.045455,0.000000,4.272727,233.181818,4.000000,78.181818,16.818182
38,Oregon,345.521739,2014.0,290.173913,51.956522,0.608696,0.000000,0.608696,0.000000,1.043478,55.043478,0.000000,289.304348,0.130435
39,Pennsylvania,359.410256,2014.0,252.717949,103.076923,0.128205,0.000000,0.128205,0.076923,2.179487,205.923077,13.282051,136.307692,1.641026
40,Puerto Rico,223.076923,2014.0,214.153846,8.769231,0.076923,0.076923,0.076923,41.461538,0.000000,36.384615,37.153846,14.923077,93.153846
41,Rhode Island,364.333333,2014.0,317.666667,45.666667,0.000000,0.000000,0.000000,0.000000,13.000000,221.333333,0.000000,129.333333,0.666667
42,South Carolina,293.526316,2014.0,244.105263,49.105263,0.052632,0.000000,0.052632,0.052632,2.578947,154.684211,10.315789,105.210526,20.684211
43,South Dakota,336.111111,2014.0,301.222222,34.555556,0.000000,0.000000,0.000000,0.000000,3.222222,198.888889,0.000000,76.555556,57.444444
44,Tennessee,277.291667,2014.0,219.958333,55.166667,0.000000,0.000000,0.000000,0.000000,2.916667,155.208333,14.458333,89.125000,15.583333
45,Texas,340.023256,2014.0,265.627907,71.930233,0.162791,0.000000,0.162791,0.116279,3.953488,201.279070,1.674419,132.000000,1.000000
46,Utah,333.133333,2014.0,251.200000,76.266667,0.466667,0.000000,0.466667,0.000000,19.466667,259.533333,0.000000,53.000000,1.133333
47,Vermont,302.750000,2014.0,259.750000,42.250000,0.000000,0.000000,0.000000,0.000000,13.250000,130.500000,0.500000,158.500000,0.000000
48,Virgin Islands,78.500000,2014.0,63.500000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,64.000000,14.500000
49,Virginia,260.771429,2014.0,230.200000,30.228571,0.028571,0.000000,0.028571,5.171429,39.142857,134.685714,1.771429,70.600000,9.400000
50,Washington,343.344828,2014.0,300.551724,40.965517,0.275862,0.000000,0.275862,0.206897,3.172414,42.517241,0.000000,288.137931,9.310345
51,West Virginia,281.000000,2014.0,233.666667,46.933333,0.000000,0.000000,0.000000,0.133333,0.000000,144.466667,43.800000,82.200000,10.400000
52,Wisconsin,294.777778,2014.0,238.037037,52.518519,0.074074,0.000000,0.074074,0.000000,0.666667,182.592593,15.148148,96.037037,0.333333
53,Wyoming,310.315789,2014.0,266.105263,43.315789,0.315789,0.000000,0.315789,0.000000,5.105263,233.842105,2.578947,28.421053,40.368421

In [39]:
grouped_p_2015 = pd.DataFrame({"Days_with_AQI": pollution_2015_states.groupby(["State"]).mean()["Days_with_AQI"], 
                                "Year": pollution_2015_states.groupby(["State"]).mean()["Year"],
                             "Good_Days": pollution_2015_states.groupby(["State"]).mean()["Good_Days"],
                             "Moderate_Days": pollution_2015_states.groupby(["State"]).mean()["Moderate_Days"], 
                             "Unhealthy_Days": pollution_2015_states.groupby(["State"]).mean()["Unhealthy_Days"],   
                             "Very_Unhealthy_Days": pollution_2015_states.groupby(["State"]).mean()["Very_Unhealthy_Days"], 
                             "Hazardous_Days": pollution_2015_states.groupby(["State"]).mean()["Unhealthy_Days"],
                             "Days_CO": pollution_2015_states.groupby(["State"]).mean()["Days_CO"],
                             "Days_NO2": pollution_2015_states.groupby(["State"]).mean()["Days_NO2"],
                             "Days_Ozone": pollution_2015_states.groupby(["State"]).mean()["Days_Ozone"],
                             "Days_SO2": pollution_2015_states.groupby(["State"]).mean()["Days_SO2"],
                             "Days_PM2_5": pollution_2015_states.groupby(["State"]).mean()["Days_PM2_5"],
                             "Days_PM10": pollution_2015_states.groupby(["State"]).mean()["Days_PM10"]})

In [40]:
grouped_p_2015_i = grouped_p_2015.reset_index()  
grouped_p_2015_i

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,287.277778,2015.0,217.777778,68.277778,0.166667,0.000000,0.166667,0.000000,0.611111,137.555556,0.333333,145.555556,3.222222
1,Alaska,255.625000,2015.0,205.875000,40.500000,5.125000,0.375000,5.125000,0.375000,0.375000,78.875000,0.250000,157.875000,17.875000
2,Arizona,359.230769,2015.0,242.692308,98.538462,2.461538,0.076923,2.461538,0.000000,2.769231,193.769231,19.692308,45.076923,97.923077
3,Arkansas,270.636364,2015.0,231.000000,39.454545,0.000000,0.000000,0.000000,0.000000,2.636364,157.727273,22.545455,87.727273,0.000000
4,California,344.166667,2015.0,196.388889,121.333333,4.629630,0.240741,4.629630,0.037037,5.425926,214.685185,0.000000,110.055556,13.962963
5,Colorado,289.935484,2015.0,225.516129,60.870968,0.161290,0.064516,0.161290,0.032258,9.354839,201.322581,0.903226,19.612903,58.709677
6,Connecticut,317.625000,2015.0,234.125000,71.750000,1.250000,0.000000,1.250000,0.250000,5.875000,205.750000,0.000000,105.375000,0.375000
7,Country Of Mexico,56.000000,2015.0,8.000000,34.000000,4.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,56.000000
8,Delaware,365.000000,2015.0,252.000000,108.666667,0.333333,0.000000,0.333333,0.000000,2.666667,254.666667,0.333333,107.333333,0.000000
9,District Of Columbia,365.000000,2015.0,217.000000,143.000000,0.000000,0.000000,0.000000,0.000000,31.000000,159.000000,0.000000,175.000000,0.000000
10,Florida,359.641026,2015.0,320.692308,38.384615,0.000000,0.000000,0.000000,0.025641,0.846154,232.589744,9.205128,106.179487,10.794872
11,Georgia,295.281250,2015.0,230.625000,63.468750,0.156250,0.031250,0.156250,0.031250,5.562500,115.218750,3.625000,170.843750,0.000000
12,Hawaii,364.250000,2015.0,259.250000,29.000000,37.000000,0.750000,37.000000,0.000000,29.250000,40.250000,92.500000,198.250000,4.000000
13,Idaho,284.000000,2015.0,236.476190,39.476190,2.285714,0.285714,2.285714,0.190476,2.428571,27.523810,21.904762,216.285714,15.666667
14,Illinois,331.038462,2015.0,274.038462,55.423077,0.076923,0.000000,0.076923,0.000000,2.769231,201.846154,52.538462,72.923077,0.961538
15,Indiana,283.622222,2015.0,218.955556,62.711111,0.155556,0.000000,0.155556,0.066667,1.711111,109.600000,57.200000,114.000000,1.044444
16,Iowa,293.789474,2015.0,222.894737,69.526316,0.157895,0.000000,0.157895,0.000000,0.894737,88.105263,17.894737,161.157895,25.736842
17,Kansas,310.909091,2015.0,267.909091,42.545455,0.000000,0.000000,0.000000,0.000000,3.000000,219.545455,1.545455,46.090909,40.727273
18,Kentucky,310.678571,2015.0,254.392857,54.535714,0.142857,0.000000,0.142857,0.000000,3.892857,198.142857,10.000000,97.785714,0.857143
19,Louisiana,315.227273,2015.0,251.090909,62.090909,0.136364,0.000000,0.136364,0.136364,4.181818,189.954545,2.363636,118.272727,0.318182
20,Maine,298.416667,2015.0,261.583333,36.166667,0.000000,0.000000,0.000000,0.000000,1.916667,191.333333,15.583333,88.166667,1.416667
21,Maryland,315.437500,2015.0,219.875000,91.875000,0.187500,0.000000,0.187500,0.062500,16.250000,186.062500,0.125000,112.875000,0.062500
22,Massachusetts,352.153846,2015.0,294.153846,56.000000,0.076923,0.000000,0.076923,0.000000,9.384615,226.307692,0.000000,116.384615,0.076923
23,Michigan,289.714286,2015.0,232.857143,54.321429,0.107143,0.000000,0.107143,0.000000,0.428571,162.000000,16.357143,109.857143,1.071429
24,Minnesota,316.904762,2015.0,281.333333,34.523810,0.047619,0.000000,0.047619,0.000000,4.904762,137.428571,0.238095,161.333333,13.000000
25,Mississippi,295.818182,2015.0,249.272727,46.363636,0.000000,0.000000,0.000000,0.000000,7.454545,166.181818,0.818182,121.363636,0.000000
26,Missouri,292.739130,2015.0,235.913043,54.130435,0.086957,0.000000,0.086957,0.000000,4.826087,145.913043,32.695652,95.043478,14.260870
27,Montana,309.894737,2015.0,254.736842,46.157895,4.315789,0.157895,4.315789,0.526316,1.473684,98.894737,4.842105,175.000000,29.157895
28,Nebraska,209.000000,2015.0,182.090909,26.454545,0.000000,0.000000,0.000000,0.090909,0.000000,63.818182,2.090909,104.636364,38.363636
29,Nevada,336.333333,2015.0,250.888889,79.666667,0.444444,0.000000,0.444444,0.000000,2.555556,194.777778,0.000000,70.333333,68.666667
30,New Hampshire,341.714286,2015.0,293.714286,46.142857,0.142857,0.000000,0.142857,0.000000,0.000000,268.285714,0.571429,72.857143,0.000000
31,New Jersey,341.875000,2015.0,257.437500,77.625000,0.250000,0.000000,0.250000,0.000000,39.312500,219.125000,0.500000,82.312500,0.625000
32,New Mexico,273.176471,2015.0,221.411765,50.647059,0.117647,0.000000,0.117647,0.000000,5.352941,173.294118,6.705882,63.823529,24.000000
33,New York,353.793103,2015.0,297.482759,53.620690,0.000000,0.000000,0.000000,0.068966,8.931034,240.517241,4.482759,99.793103,0.000000
34,North Carolina,280.488889,2015.0,227.733333,52.288889,0.000000,0.000000,0.000000,0.000000,0.577778,155.311111,11.466667,113.111111,0.022222
35,North Dakota,364.900000,2015.0,319.900000,38.500000,1.500000,0.000000,1.500000,0.000000,2.700000,246.100000,7.000000,66.200000,42.900000
36,Ohio,317.390244,2015.0,244.195122,70.317073,0.048780,0.000000,0.048780,0.195122,5.634146,149.000000,38.463415,116.195122,7.902439
37,Oklahoma,305.782609,2015.0,257.521739,47.913043,0.043478,0.000000,0.043478,0.000000,5.260870,202.217391,3.739130,74.304348,20.260870
38,Oregon,345.956522,2015.0,282.652174,56.478261,2.304348,0.043478,2.304348,0.000000,2.304348,57.739130,0.000000,285.739130,0.173913
39,Pennsylvania,361.131579,2015.0,248.710526,107.447368,0.184211,0.000000,0.184211,0.000000,2.289474,216.894737,12.315789,127.763158,1.868421
40,Puerto Rico,269.090909,2015.0,253.000000,15.636364,0.181818,0.000000,0.181818,36.363636,5.181818,51.636364,33.727273,42.727273,99.454545
41,Rhode Island,361.000000,2015.0,286.333333,69.666667,1.000000,0.000000,1.000000,0.000000,20.666667,195.666667,0.000000,144.333333,0.333333
42,South Carolina,295.631579,2015.0,258.210526,37.210526,0.000000,0.000000,0.000000,0.000000,1.578947,194.210526,0.631579,83.105263,16.105263
43,South Dakota,338.700000,2015.0,293.900000,43.100000,0.100000,0.000000,0.100000,0.000000,3.700000,162.100000,0.000000,144.700000,28.200000
44,Tennessee,264.375000,2015.0,216.166667,46.708333,0.000000,0.000000,0.000000,0.166667,3.916667,150.916667,12.583333,80.250000,16.541667
45,Texas,349.853659,2015.0,273.853659,70.048780,0.731707,0.024390,0.731707,0.024390,4.414634,218.804878,1.487805,124.609756,0.512195
46,Utah,341.428571,2015.0,250.285714,85.000000,0.285714,0.000000,0.285714,0.000000,12.214286,265.357143,0.000000,61.857143,2.000000
47,Vermont,301.750000,2015.0,256.000000,45.000000,0.000000,0.000000,0.000000,0.000000,14.750000,140.500000,0.000000,146.500000,0.000000
48,Virgin Islands,73.500000,2015.0,56.500000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,64.500000,9.000000
49,Virginia,261.000000,2015.0,228.142857,32.342857,0.000000,0.000000,0.000000,1.142857,35.057143,141.257143,0.971429,73.657143,8.914286
50,Washington,345.827586,2015.0,292.758621,48.137931,1.034483,0.068966,1.034483,0.000000,2.689655,47.448276,0.000000,290.206897,5.482759
51,West Virginia,280.466667,2015.0,234.066667,45.200000,0.066667,0.000000,0.066667,0.133333,0.000000,145.533333,40.466667,81.200000,13.133333
52,Wisconsin,291.785714,2015.0,245.857143,42.678571,0.071429,0.000000,0.071429,0.000000,0.714286,191.428571,14.535714,84.857143,0.250000
53,Wyoming,309.421053,2015.0,262.578947,45.684211,0.210526,0.000000,0.210526,0.052632,1.578947,235.894737,0.526316,29.315789,42.052632

In [41]:
grouped_p_2011_i

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.526316,2011.0,171.789474,72.368421,0.368421,0.000000,0.368421,0.105263,0.000000,158.631579,0.157895,84.894737,4.736842
1,Alaska,274.500000,2011.0,235.250000,34.875000,0.625000,0.125000,0.625000,2.125000,0.000000,75.625000,0.000000,176.250000,20.500000
2,Arizona,320.615385,2011.0,177.153846,117.000000,2.384615,1.000000,2.384615,0.000000,3.153846,167.153846,16.538462,27.769231,106.000000
3,Arkansas,216.882353,2011.0,154.470588,59.176471,0.117647,0.000000,0.117647,0.000000,3.000000,108.764706,14.764706,90.352941,0.000000
4,California,345.648148,2011.0,193.166667,120.370370,7.018519,0.370370,7.018519,0.166667,6.907407,197.425926,0.092593,129.240741,11.814815
5,Colorado,285.156250,2011.0,190.468750,85.406250,0.406250,0.031250,0.406250,0.437500,7.875000,194.312500,0.218750,17.656250,64.656250
6,Connecticut,280.875000,2011.0,221.625000,50.750000,2.500000,0.000000,2.500000,5.625000,25.000000,190.000000,1.625000,58.625000,0.000000
7,Country Of Mexico,362.500000,2011.0,220.000000,106.500000,6.000000,2.500000,6.000000,52.000000,48.500000,204.000000,0.000000,0.000000,58.000000
8,Delaware,365.000000,2011.0,250.000000,102.000000,2.333333,0.000000,2.333333,0.000000,0.333333,271.333333,0.000000,93.333333,0.000000
9,District Of Columbia,365.000000,2011.0,135.000000,214.000000,3.000000,0.000000,3.000000,0.000000,26.000000,114.000000,1.000000,224.000000,0.000000
10,Florida,347.743590,2011.0,276.000000,67.897436,0.205128,0.000000,0.205128,0.000000,0.384615,221.205128,10.897436,106.512821,8.743590
11,Georgia,295.625000,2011.0,168.343750,118.781250,0.437500,0.000000,0.437500,0.031250,4.531250,113.312500,6.625000,169.812500,1.312500
12,Hawaii,331.000000,2011.0,208.500000,54.250000,33.750000,0.000000,33.750000,1.250000,7.000000,32.500000,104.000000,184.750000,1.500000
13,Idaho,318.176471,2011.0,274.705882,40.647059,0.352941,0.000000,0.352941,0.647059,0.588235,57.117647,31.235294,178.882353,49.705882
14,Illinois,335.461538,2011.0,257.653846,71.730769,0.769231,0.000000,0.769231,3.000000,2.115385,223.461538,45.538462,61.153846,0.192308
15,Indiana,272.476190,2011.0,179.904762,85.857143,0.404762,0.000000,0.404762,1.214286,0.880952,106.261905,57.785714,105.309524,1.023810
16,Iowa,270.150000,2011.0,180.700000,87.400000,0.650000,0.000000,0.650000,0.000000,0.300000,80.950000,5.750000,160.250000,22.900000
17,Kansas,262.800000,2011.0,195.533333,61.066667,0.066667,0.000000,0.066667,0.000000,8.000000,172.466667,7.666667,42.600000,32.066667
18,Kentucky,301.200000,2011.0,214.666667,81.000000,0.433333,0.000000,0.433333,0.000000,2.766667,188.800000,15.233333,92.200000,2.200000
19,Louisiana,338.454545,2011.0,227.590909,97.818182,2.045455,0.000000,2.045455,0.000000,2.136364,209.772727,6.818182,119.272727,0.454545
20,Maine,273.916667,2011.0,247.500000,25.083333,0.250000,0.000000,0.250000,0.000000,1.583333,210.333333,0.083333,58.333333,3.583333
21,Maryland,304.066667,2011.0,190.400000,98.333333,2.933333,0.200000,2.933333,0.000000,7.000000,181.666667,0.133333,114.866667,0.400000
22,Massachusetts,329.750000,2011.0,244.166667,80.750000,0.583333,0.083333,0.583333,0.083333,9.166667,175.333333,2.250000,142.916667,0.000000
23,Michigan,245.071429,2011.0,192.214286,46.321429,0.785714,0.000000,0.785714,0.000000,1.464286,178.285714,1.285714,63.892857,0.142857
24,Minnesota,290.666667,2011.0,238.000000,51.523810,0.047619,0.000000,0.047619,0.952381,3.047619,119.285714,8.380952,154.619048,4.380952
25,Mississippi,292.307692,2011.0,195.615385,94.153846,0.000000,0.000000,0.000000,0.000000,5.307692,124.769231,1.076923,161.153846,0.000000
26,Missouri,284.772727,2011.0,180.545455,91.318182,0.954545,0.000000,0.954545,0.000000,2.545455,165.772727,17.136364,85.227273,14.090909
27,Montana,285.611111,2011.0,231.000000,50.111111,0.500000,0.000000,0.500000,0.888889,1.500000,65.166667,9.833333,173.944444,34.277778
28,Nebraska,218.727273,2011.0,174.818182,43.363636,0.000000,0.000000,0.000000,10.181818,0.000000,66.727273,2.454545,98.090909,41.272727
29,Nevada,299.700000,2011.0,235.200000,58.100000,0.200000,0.000000,0.200000,33.100000,5.400000,148.700000,0.000000,16.900000,95.600000
30,New Hampshire,341.714286,2011.0,259.428571,72.142857,1.285714,0.000000,1.285714,0.714286,0.000000,232.285714,34.428571,74.285714,0.000000
31,New Jersey,349.937500,2011.0,248.437500,88.750000,1.875000,0.000000,1.875000,3.125000,29.375000,190.062500,4.312500,122.125000,0.937500
32,New Mexico,273.833333,2011.0,197.055556,70.833333,0.333333,0.111111,0.333333,0.000000,5.000000,156.611111,1.388889,76.277778,34.555556
33,New York,347.323529,2011.0,282.764706,60.676471,0.558824,0.029412,0.558824,0.294118,9.529412,239.647059,3.441176,94.411765,0.000000
34,North Carolina,285.978261,2011.0,193.630435,87.347826,0.326087,0.000000,0.326087,0.000000,0.369565,146.826087,13.652174,125.130435,0.000000
35,North Dakota,353.555556,2011.0,322.666667,29.777778,0.000000,0.111111,0.000000,0.000000,4.000000,219.444444,50.888889,72.777778,6.444444
36,Ohio,316.441860,2011.0,211.488372,93.162791,0.697674,0.000000,0.697674,0.348837,2.418605,134.116279,55.837209,117.255814,6.465116
37,Oklahoma,331.304348,2011.0,200.956522,110.043478,0.956522,0.000000,0.956522,0.000000,3.652174,240.565217,7.826087,63.782609,15.478261
38,Oregon,328.360000,2011.0,266.840000,57.680000,0.440000,0.000000,0.440000,0.000000,0.120000,52.840000,0.000000,275.200000,0.200000
39,Pennsylvania,346.552632,2011.0,222.500000,115.105263,0.684211,0.000000,0.684211,0.105263,5.552632,177.263158,15.710526,142.315789,5.605263
40,Puerto Rico,228.230769,2011.0,223.307692,4.923077,0.000000,0.000000,0.000000,26.000000,0.000000,37.000000,68.846154,25.461538,70.923077
41,Rhode Island,314.666667,2011.0,243.666667,64.666667,0.000000,0.000000,0.000000,0.000000,3.666667,211.666667,0.000000,99.333333,0.000000
42,South Carolina,299.700000,2011.0,209.200000,86.300000,0.200000,0.000000,0.200000,0.000000,1.250000,185.800000,5.700000,88.150000,18.800000
43,South Dakota,334.000000,2011.0,296.222222,37.444444,0.000000,0.000000,0.000000,0.000000,9.666667,190.666667,0.000000,79.444444,54.222222
44,Tennessee,296.750000,2011.0,206.041667,81.166667,0.541667,0.000000,0.541667,0.041667,24.166667,180.208333,25.500000,41.291667,25.541667
45,Texas,334.955556,2011.0,227.422222,93.377778,1.933333,0.044444,1.933333,0.000000,3.888889,201.711111,1.666667,126.377778,1.311111
46,Utah,310.200000,2011.0,200.466667,99.466667,2.200000,0.600000,2.200000,0.000000,23.733333,219.866667,0.200000,65.133333,1.266667
47,Vermont,274.000000,2011.0,205.500000,66.250000,0.000000,0.000000,0.000000,1.500000,2.750000,107.500000,2.000000,160.250000,0.000000
48,Virgin Islands,240.500000,2011.0,218.000000,19.500000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,169.500000,63.500000,7.500000
49,Virginia,252.631579,2011.0,198.973684,49.842105,0.421053,0.000000,0.421053,0.368421,39.789474,127.500000,4.026316,69.789474,11.157895
50,Washington,348.133333,2011.0,301.366667,44.766667,0.433333,0.000000,0.433333,0.266667,1.066667,45.766667,0.066667,291.933333,9.033333
51,West Virginia,280.562500,2011.0,210.500000,65.937500,0.500000,0.000000,0.500000,0.000000,0.000000,126.875000,67.250000,81.125000,5.312500
52,Wisconsin,246.233333,2011.0,194.266667,47.200000,0.400000,0.033333,0.400000,0.000000,0.666667,175.500000,8.533333,59.233333,2.300000
53,Wyoming,298.000000,2011.0,235.473684,60.157895,0.263158,0.157895,0.263158,0.210526,3.210526,176.315789,21.052632,30.526316,66.684211

In [42]:
# drop Puerto Rico data
grouped_states_pr11 = grouped_p_2011_i.drop(index = 40)
grouped_states_pr12 = grouped_p_2012_i.drop(index = 40)
grouped_states_pr13 = grouped_p_2013_i.drop(index = 40)
grouped_states_pr14 = grouped_p_2014_i.drop(index = 40)
grouped_states_pr15 = grouped_p_2015_i.drop(index = 40)

In [43]:
grouped_states_pr15.tail(15)

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
38,Oregon,345.956522,2015.0,282.652174,56.478261,2.304348,0.043478,2.304348,0.000000,2.304348,57.739130,0.000000,285.739130,0.173913
39,Pennsylvania,361.131579,2015.0,248.710526,107.447368,0.184211,0.000000,0.184211,0.000000,2.289474,216.894737,12.315789,127.763158,1.868421
41,Rhode Island,361.000000,2015.0,286.333333,69.666667,1.000000,0.000000,1.000000,0.000000,20.666667,195.666667,0.000000,144.333333,0.333333
42,South Carolina,295.631579,2015.0,258.210526,37.210526,0.000000,0.000000,0.000000,0.000000,1.578947,194.210526,0.631579,83.105263,16.105263
43,South Dakota,338.700000,2015.0,293.900000,43.100000,0.100000,0.000000,0.100000,0.000000,3.700000,162.100000,0.000000,144.700000,28.200000
44,Tennessee,264.375000,2015.0,216.166667,46.708333,0.000000,0.000000,0.000000,0.166667,3.916667,150.916667,12.583333,80.250000,16.541667
45,Texas,349.853659,2015.0,273.853659,70.048780,0.731707,0.024390,0.731707,0.024390,4.414634,218.804878,1.487805,124.609756,0.512195
46,Utah,341.428571,2015.0,250.285714,85.000000,0.285714,0.000000,0.285714,0.000000,12.214286,265.357143,0.000000,61.857143,2.000000
47,Vermont,301.750000,2015.0,256.000000,45.000000,0.000000,0.000000,0.000000,0.000000,14.750000,140.500000,0.000000,146.500000,0.000000
48,Virgin Islands,73.500000,2015.0,56.500000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,64.500000,9.000000
49,Virginia,261.000000,2015.0,228.142857,32.342857,0.000000,0.000000,0.000000,1.142857,35.057143,141.257143,0.971429,73.657143,8.914286
50,Washington,345.827586,2015.0,292.758621,48.137931,1.034483,0.068966,1.034483,0.000000,2.689655,47.448276,0.000000,290.206897,5.482759
51,West Virginia,280.466667,2015.0,234.066667,45.200000,0.066667,0.000000,0.066667,0.133333,0.000000,145.533333,40.466667,81.200000,13.133333
52,Wisconsin,291.785714,2015.0,245.857143,42.678571,0.071429,0.000000,0.071429,0.000000,0.714286,191.428571,14.535714,84.857143,0.250000
53,Wyoming,309.421053,2015.0,262.578947,45.684211,0.210526,0.000000,0.210526,0.052632,1.578947,235.894737,0.526316,29.315789,42.052632

In [44]:
# drop Virgin Islands data
grouped_states_vi11 = grouped_states_pr11.drop(index = 48)
grouped_states_vi12 = grouped_states_pr12.drop(index = 48)
grouped_states_vi13 = grouped_states_pr13.drop(index = 48)
grouped_states_vi14 = grouped_states_pr14.drop(index = 48)
grouped_states_vi15 = grouped_states_pr15.drop(index = 48)
grouped_states_vi15.tail(6)

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
47,Vermont,301.750000,2015.0,256.000000,45.000000,0.000000,0.000000,0.000000,0.000000,14.750000,140.500000,0.000000,146.500000,0.000000
49,Virginia,261.000000,2015.0,228.142857,32.342857,0.000000,0.000000,0.000000,1.142857,35.057143,141.257143,0.971429,73.657143,8.914286
50,Washington,345.827586,2015.0,292.758621,48.137931,1.034483,0.068966,1.034483,0.000000,2.689655,47.448276,0.000000,290.206897,5.482759
51,West Virginia,280.466667,2015.0,234.066667,45.200000,0.066667,0.000000,0.066667,0.133333,0.000000,145.533333,40.466667,81.200000,13.133333
52,Wisconsin,291.785714,2015.0,245.857143,42.678571,0.071429,0.000000,0.071429,0.000000,0.714286,191.428571,14.535714,84.857143,0.250000
53,Wyoming,309.421053,2015.0,262.578947,45.684211,0.210526,0.000000,0.210526,0.052632,1.578947,235.894737,0.526316,29.315789,42.052632

In [45]:
# drop Mexico data
grouped_states_clean_2011 = grouped_states_vi11.drop(index = 7)
grouped_states_clean_2012 = grouped_states_vi12.drop(index = 7)
grouped_states_clean_2013 = grouped_states_vi13.drop(index = 7)
grouped_states_clean_2014 = grouped_states_vi14.drop(index = 7)
grouped_states_clean_2015 = grouped_states_vi15.drop(index = 7)
grouped_states_clean_2015.head(8)

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,287.277778,2015.0,217.777778,68.277778,0.166667,0.000000,0.166667,0.000000,0.611111,137.555556,0.333333,145.555556,3.222222
1,Alaska,255.625000,2015.0,205.875000,40.500000,5.125000,0.375000,5.125000,0.375000,0.375000,78.875000,0.250000,157.875000,17.875000
2,Arizona,359.230769,2015.0,242.692308,98.538462,2.461538,0.076923,2.461538,0.000000,2.769231,193.769231,19.692308,45.076923,97.923077
3,Arkansas,270.636364,2015.0,231.000000,39.454545,0.000000,0.000000,0.000000,0.000000,2.636364,157.727273,22.545455,87.727273,0.000000
4,California,344.166667,2015.0,196.388889,121.333333,4.629630,0.240741,4.629630,0.037037,5.425926,214.685185,0.000000,110.055556,13.962963
5,Colorado,289.935484,2015.0,225.516129,60.870968,0.161290,0.064516,0.161290,0.032258,9.354839,201.322581,0.903226,19.612903,58.709677
6,Connecticut,317.625000,2015.0,234.125000,71.750000,1.250000,0.000000,1.250000,0.250000,5.875000,205.750000,0.000000,105.375000,0.375000
8,Delaware,365.000000,2015.0,252.000000,108.666667,0.333333,0.000000,0.333333,0.000000,2.666667,254.666667,0.333333,107.333333,0.000000

In [46]:
# reset indicies
grouped_states_2011_i = grouped_states_clean_2011.reset_index(drop=True)  
grouped_states_2012_i = grouped_states_clean_2012.reset_index(drop=True)  
grouped_states_2013_i = grouped_states_clean_2013.reset_index(drop=True)  
grouped_states_2014_i = grouped_states_clean_2014.reset_index(drop=True)  
grouped_states_2015_i = grouped_states_clean_2015.reset_index(drop=True)

In [47]:
grouped_states_2014_i.tail()

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
46,Virginia,260.771429,2014.0,230.200000,30.228571,0.028571,0.0,0.028571,5.171429,39.142857,134.685714,1.771429,70.600000,9.400000
47,Washington,343.344828,2014.0,300.551724,40.965517,0.275862,0.0,0.275862,0.206897,3.172414,42.517241,0.000000,288.137931,9.310345
48,West Virginia,281.000000,2014.0,233.666667,46.933333,0.000000,0.0,0.000000,0.133333,0.000000,144.466667,43.800000,82.200000,10.400000
49,Wisconsin,294.777778,2014.0,238.037037,52.518519,0.074074,0.0,0.074074,0.000000,0.666667,182.592593,15.148148,96.037037,0.333333
50,Wyoming,310.315789,2014.0,266.105263,43.315789,0.315789,0.0,0.315789,0.000000,5.105263,233.842105,2.578947,28.421053,40.368421

In [48]:
# Stack tables together using concat

pollution_concat_1 = pd.concat([grouped_states_2011_i, grouped_states_2012_i], axis =0)
pollution_concat_2 = pd.concat([pollution_concat_1, grouped_states_2013_i], axis =0)
pollution_concat_3 = pd.concat([pollution_concat_2, grouped_states_2014_i], axis =0)
pollution_all = pd.concat([pollution_concat_3, grouped_states_2015_i], axis =0)
pollution_all

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.526316,2011.0,171.789474,72.368421,0.368421,0.000000,0.368421,0.105263,0.000000,158.631579,0.157895,84.894737,4.736842
1,Alaska,274.500000,2011.0,235.250000,34.875000,0.625000,0.125000,0.625000,2.125000,0.000000,75.625000,0.000000,176.250000,20.500000
2,Arizona,320.615385,2011.0,177.153846,117.000000,2.384615,1.000000,2.384615,0.000000,3.153846,167.153846,16.538462,27.769231,106.000000
3,Arkansas,216.882353,2011.0,154.470588,59.176471,0.117647,0.000000,0.117647,0.000000,3.000000,108.764706,14.764706,90.352941,0.000000
4,California,345.648148,2011.0,193.166667,120.370370,7.018519,0.370370,7.018519,0.166667,6.907407,197.425926,0.092593,129.240741,11.814815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,Virginia,261.000000,2015.0,228.142857,32.342857,0.000000,0.000000,0.000000,1.142857,35.057143,141.257143,0.971429,73.657143,8.914286
47,Washington,345.827586,2015.0,292.758621,48.137931,1.034483,0.068966,1.034483,0.000000,2.689655,47.448276,0.000000,290.206897,5.482759
48,West Virginia,280.466667,2015.0,234.066667,45.200000,0.066667,0.000000,0.066667,0.133333,0.000000,145.533333,40.466667,81.200000,13.133333
49,Wisconsin,291.785714,2015.0,245.857143,42.678571,0.071429,0.000000,0.071429,0.000000,0.714286,191.428571,14.535714,84.857143,0.250000
50,Wyoming,309.421053,2015.0,262.578947,45.684211,0.210526,0.000000,0.210526,0.052632,1.578947,235.894737,0.526316,29.315789,42.052632

In [49]:
pollution_all.head(53)

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.526316,2011.0,171.789474,72.368421,0.368421,0.000000,0.368421,0.105263,0.000000,158.631579,0.157895,84.894737,4.736842
1,Alaska,274.500000,2011.0,235.250000,34.875000,0.625000,0.125000,0.625000,2.125000,0.000000,75.625000,0.000000,176.250000,20.500000
2,Arizona,320.615385,2011.0,177.153846,117.000000,2.384615,1.000000,2.384615,0.000000,3.153846,167.153846,16.538462,27.769231,106.000000
3,Arkansas,216.882353,2011.0,154.470588,59.176471,0.117647,0.000000,0.117647,0.000000,3.000000,108.764706,14.764706,90.352941,0.000000
4,California,345.648148,2011.0,193.166667,120.370370,7.018519,0.370370,7.018519,0.166667,6.907407,197.425926,0.092593,129.240741,11.814815
5,Colorado,285.156250,2011.0,190.468750,85.406250,0.406250,0.031250,0.406250,0.437500,7.875000,194.312500,0.218750,17.656250,64.656250
6,Connecticut,280.875000,2011.0,221.625000,50.750000,2.500000,0.000000,2.500000,5.625000,25.000000,190.000000,1.625000,58.625000,0.000000
7,Delaware,365.000000,2011.0,250.000000,102.000000,2.333333,0.000000,2.333333,0.000000,0.333333,271.333333,0.000000,93.333333,0.000000
8,District Of Columbia,365.000000,2011.0,135.000000,214.000000,3.000000,0.000000,3.000000,0.000000,26.000000,114.000000,1.000000,224.000000,0.000000
9,Florida,347.743590,2011.0,276.000000,67.897436,0.205128,0.000000,0.205128,0.000000,0.384615,221.205128,10.897436,106.512821,8.743590
10,Georgia,295.625000,2011.0,168.343750,118.781250,0.437500,0.000000,0.437500,0.031250,4.531250,113.312500,6.625000,169.812500,1.312500
11,Hawaii,331.000000,2011.0,208.500000,54.250000,33.750000,0.000000,33.750000,1.250000,7.000000,32.500000,104.000000,184.750000,1.500000
12,Idaho,318.176471,2011.0,274.705882,40.647059,0.352941,0.000000,0.352941,0.647059,0.588235,57.117647,31.235294,178.882353,49.705882
13,Illinois,335.461538,2011.0,257.653846,71.730769,0.769231,0.000000,0.769231,3.000000,2.115385,223.461538,45.538462,61.153846,0.192308
14,Indiana,272.476190,2011.0,179.904762,85.857143,0.404762,0.000000,0.404762,1.214286,0.880952,106.261905,57.785714,105.309524,1.023810
15,Iowa,270.150000,2011.0,180.700000,87.400000,0.650000,0.000000,0.650000,0.000000,0.300000,80.950000,5.750000,160.250000,22.900000
16,Kansas,262.800000,2011.0,195.533333,61.066667,0.066667,0.000000,0.066667,0.000000,8.000000,172.466667,7.666667,42.600000,32.066667
17,Kentucky,301.200000,2011.0,214.666667,81.000000,0.433333,0.000000,0.433333,0.000000,2.766667,188.800000,15.233333,92.200000,2.200000
18,Louisiana,338.454545,2011.0,227.590909,97.818182,2.045455,0.000000,2.045455,0.000000,2.136364,209.772727,6.818182,119.272727,0.454545
19,Maine,273.916667,2011.0,247.500000,25.083333,0.250000,0.000000,0.250000,0.000000,1.583333,210.333333,0.083333,58.333333,3.583333
20,Maryland,304.066667,2011.0,190.400000,98.333333,2.933333,0.200000,2.933333,0.000000,7.000000,181.666667,0.133333,114.866667,0.400000
21,Massachusetts,329.750000,2011.0,244.166667,80.750000,0.583333,0.083333,0.583333,0.083333,9.166667,175.333333,2.250000,142.916667,0.000000
22,Michigan,245.071429,2011.0,192.214286,46.321429,0.785714,0.000000,0.785714,0.000000,1.464286,178.285714,1.285714,63.892857,0.142857
23,Minnesota,290.666667,2011.0,238.000000,51.523810,0.047619,0.000000,0.047619,0.952381,3.047619,119.285714,8.380952,154.619048,4.380952
24,Mississippi,292.307692,2011.0,195.615385,94.153846,0.000000,0.000000,0.000000,0.000000,5.307692,124.769231,1.076923,161.153846,0.000000
25,Missouri,284.772727,2011.0,180.545455,91.318182,0.954545,0.000000,0.954545,0.000000,2.545455,165.772727,17.136364,85.227273,14.090909
26,Montana,285.611111,2011.0,231.000000,50.111111,0.500000,0.000000,0.500000,0.888889,1.500000,65.166667,9.833333,173.944444,34.277778
27,Nebraska,218.727273,2011.0,174.818182,43.363636,0.000000,0.000000,0.000000,10.181818,0.000000,66.727273,2.454545,98.090909,41.272727
28,Nevada,299.700000,2011.0,235.200000,58.100000,0.200000,0.000000,0.200000,33.100000,5.400000,148.700000,0.000000,16.900000,95.600000
29,New Hampshire,341.714286,2011.0,259.428571,72.142857,1.285714,0.000000,1.285714,0.714286,0.000000,232.285714,34.428571,74.285714,0.000000
30,New Jersey,349.937500,2011.0,248.437500,88.750000,1.875000,0.000000,1.875000,3.125000,29.375000,190.062500,4.312500,122.125000,0.937500
31,New Mexico,273.833333,2011.0,197.055556,70.833333,0.333333,0.111111,0.333333,0.000000,5.000000,156.611111,1.388889,76.277778,34.555556
32,New York,347.323529,2011.0,282.764706,60.676471,0.558824,0.029412,0.558824,0.294118,9.529412,239.647059,3.441176,94.411765,0.000000
33,North Carolina,285.978261,2011.0,193.630435,87.347826,0.326087,0.000000,0.326087,0.000000,0.369565,146.826087,13.652174,125.130435,0.000000
34,North Dakota,353.555556,2011.0,322.666667,29.777778,0.000000,0.111111,0.000000,0.000000,4.000000,219.444444,50.888889,72.777778,6.444444
35,Ohio,316.441860,2011.0,211.488372,93.162791,0.697674,0.000000,0.697674,0.348837,2.418605,134.116279,55.837209,117.255814,6.465116
36,Oklahoma,331.304348,2011.0,200.956522,110.043478,0.956522,0.000000,0.956522,0.000000,3.652174,240.565217,7.826087,63.782609,15.478261
37,Oregon,328.360000,2011.0,266.840000,57.680000,0.440000,0.000000,0.440000,0.000000,0.120000,52.840000,0.000000,275.200000,0.200000
38,Pennsylvania,346.552632,2011.0,222.500000,115.105263,0.684211,0.000000,0.684211,0.105263,5.552632,177.263158,15.710526,142.315789,5.605263
39,Rhode Island,314.666667,2011.0,243.666667,64.666667,0.000000,0.000000,0.000000,0.000000,3.666667,211.666667,0.000000,99.333333,0.000000
40,South Carolina,299.700000,2011.0,209.200000,86.300000,0.200000,0.000000,0.200000,0.000000,1.250000,185.800000,5.700000,88.150000,18.800000
41,South Dakota,334.000000,2011.0,296.222222,37.444444,0.000000,0.000000,0.000000,0.000000,9.666667,190.666667,0.000000,79.444444,54.222222
42,Tennessee,296.750000,2011.0,206.041667,81.166667,0.541667,0.000000,0.541667,0.041667,24.166667,180.208333,25.500000,41.291667,25.541667
43,Texas,334.955556,2011.0,227.422222,93.377778,1.933333,0.044444,1.933333,0.000000,3.888889,201.711111,1.666667,126.377778,1.311111
44,Utah,310.200000,2011.0,200.466667,99.466667,2.200000,0.600000,2.200000,0.000000,23.733333,219.866667,0.200000,65.133333,1.266667
45,Vermont,274.000000,2011.0,205.500000,66.250000,0.000000,0.000000,0.000000,1.500000,2.750000,107.500000,2.000000,160.250000,0.000000
46,Virginia,252.631579,2011.0,198.973684,49.842105,0.421053,0.000000,0.421053,0.368421,39.789474,127.500000,4.026316,69.789474,11.157895
47,Washington,348.133333,2011.0,301.366667,44.766667,0.433333,0.000000,0.433333,0.266667,1.066667,45.766667,0.066667,291.933333,9.033333
48,West Virginia,280.562500,2011.0,210.500000,65.937500,0.500000,0.000000,0.500000,0.000000,0.000000,126.875000,67.250000,81.125000,5.312500
49,Wisconsin,246.233333,2011.0,194.266667,47.200000,0.400000,0.033333,0.400000,0.000000,0.666667,175.500000,8.533333,59.233333,2.300000
50,Wyoming,298.000000,2011.0,235.473684,60.157895,0.263158,0.157895,0.263158,0.210526,3.210526,176.315789,21.052632,30.526316,66.684211
0,Alabama,263.588235,2012.0,201.000000,58.823529,0.235294,0.000000,0.235294,0.000000,0.000000,174.529412,0.411765,85.117647,3.529412
1,Alaska,301.250000,2012.0,258.625000,36.625000,3.125000,0.250000,3.125000,1.375000,0.000000,95.250000,0.875000,152.750000,51.000000

In [50]:
pollution_stats = pollution_all.reset_index(drop=True)
pollution_stats

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.526316,2011.0,171.789474,72.368421,0.368421,0.000000,0.368421,0.105263,0.000000,158.631579,0.157895,84.894737,4.736842
1,Alaska,274.500000,2011.0,235.250000,34.875000,0.625000,0.125000,0.625000,2.125000,0.000000,75.625000,0.000000,176.250000,20.500000
2,Arizona,320.615385,2011.0,177.153846,117.000000,2.384615,1.000000,2.384615,0.000000,3.153846,167.153846,16.538462,27.769231,106.000000
3,Arkansas,216.882353,2011.0,154.470588,59.176471,0.117647,0.000000,0.117647,0.000000,3.000000,108.764706,14.764706,90.352941,0.000000
4,California,345.648148,2011.0,193.166667,120.370370,7.018519,0.370370,7.018519,0.166667,6.907407,197.425926,0.092593,129.240741,11.814815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Virginia,261.000000,2015.0,228.142857,32.342857,0.000000,0.000000,0.000000,1.142857,35.057143,141.257143,0.971429,73.657143,8.914286
251,Washington,345.827586,2015.0,292.758621,48.137931,1.034483,0.068966,1.034483,0.000000,2.689655,47.448276,0.000000,290.206897,5.482759
252,West Virginia,280.466667,2015.0,234.066667,45.200000,0.066667,0.000000,0.066667,0.133333,0.000000,145.533333,40.466667,81.200000,13.133333
253,Wisconsin,291.785714,2015.0,245.857143,42.678571,0.071429,0.000000,0.071429,0.000000,0.714286,191.428571,14.535714,84.857143,0.250000
254,Wyoming,309.421053,2015.0,262.578947,45.684211,0.210526,0.000000,0.210526,0.052632,1.578947,235.894737,0.526316,29.315789,42.052632

In [51]:
# formatting
pollution_formatted = pollution_stats.round(2)
pollution_formatted["Year"] = pollution_formatted["Year"].astype(float).map("{:.0f}".format)
pollution_formatted

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.53,2011,171.79,72.37,0.37,0.00,0.37,0.11,0.00,158.63,0.16,84.89,4.74
1,Alaska,274.50,2011,235.25,34.88,0.62,0.12,0.62,2.12,0.00,75.62,0.00,176.25,20.50
2,Arizona,320.62,2011,177.15,117.00,2.38,1.00,2.38,0.00,3.15,167.15,16.54,27.77,106.00
3,Arkansas,216.88,2011,154.47,59.18,0.12,0.00,0.12,0.00,3.00,108.76,14.76,90.35,0.00
4,California,345.65,2011,193.17,120.37,7.02,0.37,7.02,0.17,6.91,197.43,0.09,129.24,11.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Virginia,261.00,2015,228.14,32.34,0.00,0.00,0.00,1.14,35.06,141.26,0.97,73.66,8.91
251,Washington,345.83,2015,292.76,48.14,1.03,0.07,1.03,0.00,2.69,47.45,0.00,290.21,5.48
252,West Virginia,280.47,2015,234.07,45.20,0.07,0.00,0.07,0.13,0.00,145.53,40.47,81.20,13.13
253,Wisconsin,291.79,2015,245.86,42.68,0.07,0.00,0.07,0.00,0.71,191.43,14.54,84.86,0.25
254,Wyoming,309.42,2015,262.58,45.68,0.21,0.00,0.21,0.05,1.58,235.89,0.53,29.32,42.05

In [52]:
pollution_all = pollution_formatted
pollution_all

,State,Days_with_AQI,Year,Good_Days,Moderate_Days,Unhealthy_Days,Very_Unhealthy_Days,Hazardous_Days,Days_CO,Days_NO2,Days_Ozone,Days_SO2,Days_PM2_5,Days_PM10
0,Alabama,248.53,2011,171.79,72.37,0.37,0.00,0.37,0.11,0.00,158.63,0.16,84.89,4.74
1,Alaska,274.50,2011,235.25,34.88,0.62,0.12,0.62,2.12,0.00,75.62,0.00,176.25,20.50
2,Arizona,320.62,2011,177.15,117.00,2.38,1.00,2.38,0.00,3.15,167.15,16.54,27.77,106.00
3,Arkansas,216.88,2011,154.47,59.18,0.12,0.00,0.12,0.00,3.00,108.76,14.76,90.35,0.00
4,California,345.65,2011,193.17,120.37,7.02,0.37,7.02,0.17,6.91,197.43,0.09,129.24,11.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Virginia,261.00,2015,228.14,32.34,0.00,0.00,0.00,1.14,35.06,141.26,0.97,73.66,8.91
251,Washington,345.83,2015,292.76,48.14,1.03,0.07,1.03,0.00,2.69,47.45,0.00,290.21,5.48
252,West Virginia,280.47,2015,234.07,45.20,0.07,0.00,0.07,0.13,0.00,145.53,40.47,81.20,13.13
253,Wisconsin,291.79,2015,245.86,42.68,0.07,0.00,0.07,0.00,0.71,191.43,14.54,84.86,0.25
254,Wyoming,309.42,2015,262.58,45.68,0.21,0.00,0.21,0.05,1.58,235.89,0.53,29.32,42.05

In [53]:
# Export to csv

pollution_all.to_csv('..\Resources\Tableau_clean\pollution_all.csv', index=False)